#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
#ifndef PRCONFIGURATION_SWIFT_H
#define PRCONFIGURATION_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import PRSyntacticSugar;
#endif

#import <PRConfiguration/PRConfiguration.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PRConfiguration",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC15PRConfiguration9ATTConfig")
@interface ATTConfig : NSObject
@property (nonatomic, readonly) BOOL isPermissionRequestEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AdsType;

SWIFT_CLASS("_TtC15PRConfiguration8AdConfig")
@interface AdConfig : NSObject
@property (nonatomic, readonly) BOOL simulateGoogleAds;
@property (nonatomic, readonly, strong) AdsType * _Nonnull type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class PRConfigKey;

SWIFT_CLASS("_TtC15PRConfiguration11AdConfigKey")
@interface AdConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull type;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull googleAdsEnabled;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull htmlAdsEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_RESILIENT_CLASS("_TtC15PRConfiguration7AdsType")
@interface AdsType : _PROptionSet
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AdsType * _Nonnull html;)
+ (AdsType * _Nonnull)html SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AdsType * _Nonnull google;)
+ (AdsType * _Nonnull)google SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithRawValue:(NSInteger)rawValue OBJC_DESIGNATED_INITIALIZER;
@end

@class AnalyticsUserId;
@class MainMenuAnalyticsConfig;
@class FirebaseAnalyticsConfig;
@class ReadingAnalyticsConfig;
@class ComScoreAnalyticsConfig;
@class TreasureDataAnalyticsConfig;

SWIFT_CLASS("_TtC15PRConfiguration15AnalyticsConfig")
@interface AnalyticsConfig : NSObject
@property (nonatomic, readonly, strong) AnalyticsUserId * _Nonnull userIdType;
@property (nonatomic, readonly, strong) MainMenuAnalyticsConfig * _Nonnull mainMenu;
@property (nonatomic, readonly, strong) FirebaseAnalyticsConfig * _Nonnull firebase;
@property (nonatomic, readonly, strong) ReadingAnalyticsConfig * _Nonnull readingConfig;
@property (nonatomic, readonly, strong) ComScoreAnalyticsConfig * _Nonnull comScore;
@property (nonatomic, readonly, strong) TreasureDataAnalyticsConfig * _Nonnull treasureData;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface AnalyticsConfig (SWIFT_EXTENSION(PRConfiguration))
+ (void)registerDependencies;
@end

@class FirebaseAnalyticsConfigKey;
@class ReadingAnalyticsConfigKey;
@class TreasureDataAnalyticsConfigKey;

SWIFT_CLASS("_TtC15PRConfiguration18AnalyticsConfigKey")
@interface AnalyticsConfigKey : NSObject
@property (nonatomic, readonly, strong) FirebaseAnalyticsConfigKey * _Nonnull firebase;
@property (nonatomic, readonly, strong) ReadingAnalyticsConfigKey * _Nonnull reading;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull userIdType;
@property (nonatomic, readonly, strong) TreasureDataAnalyticsConfigKey * _Nonnull treasureData;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_RESILIENT_CLASS("_TtC15PRConfiguration15AnalyticsUserId")
@interface AnalyticsUserId : _PROptionSet
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AnalyticsUserId * _Nonnull accountNumber;)
+ (AnalyticsUserId * _Nonnull)accountNumber SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AnalyticsUserId * _Nonnull internalRefNumber;)
+ (AnalyticsUserId * _Nonnull)internalRefNumber SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithRawValue:(NSInteger)rawValue OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration13AppMenuConfig")
@interface AppMenuConfig : NSObject
/// In case of branded item opens a special screen for BE apps instead of default more popup
@property (nonatomic, readonly) BOOL showMoreItemsInPopUp;
@property (nonatomic, readonly) PRAppMenuItemAbsence absence;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration16AppMenuConfigKey")
@interface AppMenuConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull catalogPanelMode;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull initialPanel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration16ArticleConfigKey")
@interface ArticleConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull numberOfLinesForPreview;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull detailsViewLightBackgroundColor;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull detailsViewLightTitleColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

SWIFT_CLASS("_TtC15PRConfiguration17ArticleFontConfig")
@interface ArticleFontConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable title;
@property (nonatomic, readonly, copy) NSString * _Nonnull subtitle;
@property (nonatomic, readonly, copy) NSString * _Nullable byline;
@property (nonatomic, readonly, copy) NSString * _Nonnull body;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ArticleGalleryCaptionPosition, open) {
  ArticleGalleryCaptionPositionAutomatic = 0,
  ArticleGalleryCaptionPositionUnderImage = 1,
};


SWIFT_CLASS("_TtC15PRConfiguration11Auth0Config")
@interface Auth0Config : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration22AuthorizationConfigKey")
@interface AuthorizationConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull type;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull frequency;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull frequencyDays;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, AuthorizationType, open) {
  AuthorizationTypeOptional = 0,
  AuthorizationTypeMandatory = 1,
};


SWIFT_CLASS("_TtC15PRConfiguration16BookReaderConfig")
@interface BookReaderConfig : NSObject
@property (nonatomic, readonly) NSInteger locationDivider;
@property (nonatomic, readonly) NSInteger defaultFontSize;
@property (nonatomic, readonly) BOOL isCopyButtonAvailable;
@property (nonatomic, readonly) BOOL isTextSpacingAvailable;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC15PRConfiguration26CancellationAdvisoryConfig")
@interface CancellationAdvisoryConfig : NSObject
@property (nonatomic, readonly) BOOL isEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration29CancellationAdvisoryConfigKey")
@interface CancellationAdvisoryConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull enabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration16CatalogConfigKey")
@interface CatalogConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull presscatalogUpdateDisabled;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull thumbnailStretchingEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration23ComScoreAnalyticsConfig")
@interface ComScoreAnalyticsConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable publisherId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration14CoreDataConfig")
@interface CoreDataConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull storeType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration21CustomerSupportConfig")
@interface CustomerSupportConfig : NSObject
@property (nonatomic, readonly) BOOL show;
@property (nonatomic, readonly, copy) NSString * _Nonnull email;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable emails;
@property (nonatomic, readonly, copy) NSString * _Nullable phone;
@property (nonatomic, readonly, copy) NSString * _Nullable privacyPolicyURL;
@property (nonatomic, readonly, copy) NSString * _Nullable termsOfUseURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull manageSubscriptionURL;
@property (nonatomic, readonly) BOOL hideFeedbackEmailQuestion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration24CustomerSupportConfigKey")
@interface CustomerSupportConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull show;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull email;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull emails;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull phone;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull privacyPolicyURL;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull termsOfUseURL;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull manageSubscriptionURL;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull hideFeedbackEmailQuestion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration25ExternalLinkAccountConfig")
@interface ExternalLinkAccountConfig : NSObject
@property (nonatomic, readonly) BOOL isEnabled;
@property (nonatomic, readonly, copy) NSString * _Nonnull developerName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration19FeaturedRadioConfig")
@interface FeaturedRadioConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_RESILIENT_CLASS("_TtC15PRConfiguration14FeedNavigation")
@interface FeedNavigation : _PROptionSet
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FeedNavigation * _Nonnull button;)
+ (FeedNavigation * _Nonnull)button SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FeedNavigation * _Nonnull tabs;)
+ (FeedNavigation * _Nonnull)tabs SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithRawValue:(NSInteger)rawValue OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration23FirebaseAnalyticsConfig")
@interface FirebaseAnalyticsConfig : NSObject
@property (nonatomic, readonly) BOOL isAnalyticsEnabled;
@property (nonatomic, readonly) BOOL isPushEnabled;
@property (nonatomic, readonly, copy) NSString * _Nullable userIdKey;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration26FirebaseAnalyticsConfigKey")
@interface FirebaseAnalyticsConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull userIdKey;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration10FontConfig")
@interface FontConfig : NSObject
@property (nonatomic, readonly) BOOL isFontSwizzlingEnabled;
@property (nonatomic, readonly, strong) ArticleFontConfig * _Nonnull article;
@property (nonatomic, readonly, copy) NSString * _Nullable mainFont;
@property (nonatomic, readonly, copy) NSString * _Nullable mainBoldFont;
@property (nonatomic, readonly, copy) NSString * _Nullable secondaryFont;
@property (nonatomic, readonly, copy) NSString * _Nullable secondaryBoldFont;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface FontConfig (SWIFT_EXTENSION(PRConfiguration))
+ (void)registerDependencies;
@end


SWIFT_CLASS("_TtC15PRConfiguration18GlobalSearchConfig")
@interface GlobalSearchConfig : NSObject
@property (nonatomic, readonly) BOOL isEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration21GlobalSearchConfigKey")
@interface GlobalSearchConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull enabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class HomeFeedConfig;

SWIFT_CLASS("_TtC15PRConfiguration10HomeConfig")
@interface HomeConfig : NSObject
@property (nonatomic, readonly, strong) HomeFeedConfig * _Nonnull feed;
@property (nonatomic, readonly) BOOL displayFavoriteIssues;
@property (nonatomic, readonly) BOOL isSourcesViewDisabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration14HomeFeedConfig")
@interface HomeFeedConfig : NSObject
@property (nonatomic, readonly, strong) FeedNavigation * _Nonnull navigation;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration9IAPConfig")
@interface IAPConfig : NSObject
@property (nonatomic, readonly) BOOL isSaveMoneyTextEnabled;
@property (nonatomic, readonly) BOOL decodeReceiptsLocaly;
@property (nonatomic, readonly) BOOL isSelectProductEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration13LibraryConfig")
@interface LibraryConfig : NSObject
@property (nonatomic, readonly) BOOL renewableIssueLicense;
@property (nonatomic, readonly) BOOL keepExpiredItems;
/// Number of seconds book content is available to read in offline mode AFTER it was opened offline first time.
/// <code>Default value</code> : 2 weeks (1209600 seconds)
@property (nonatomic, readonly) NSTimeInterval bookOfflineAccessPeriod;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration16LibraryConfigKey")
@interface LibraryConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull bookOfflineAccessPeriod;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull keepExpiredItems;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull renewableIssueLicense;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration17LocalServerConfig")
@interface LocalServerConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable serverURL;
@property (nonatomic, readonly) BOOL cleanDownloadedContentAfterDeauthorization;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration20LocalServerConfigKey")
@interface LocalServerConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull serverURL;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull cleanDownloadedContentAfterDeauthorization;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration21LowCreditsAlertConfig")
@interface LowCreditsAlertConfig : NSObject
@property (nonatomic, readonly) NSTimeInterval reappearanceTimeInterval;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration24LowCreditsAlertConfigKey")
@interface LowCreditsAlertConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull reappearanceTimeInterval;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration23MainMenuAnalyticsConfig")
@interface MainMenuAnalyticsConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable forYouValue;
@property (nonatomic, readonly, copy) NSString * _Nullable browseValue;
@property (nonatomic, readonly, copy) NSString * _Nullable downloadedValue;
@property (nonatomic, readonly, copy) NSString * _Nullable accountsValue;
@property (nonatomic, readonly, copy) NSString * _Nullable aboutUsValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration15MigrationConfig")
@interface MigrationConfig : NSObject
@property (nonatomic) BOOL bookLibraryMigrated;
@property (nonatomic) BOOL bookReadingPositionsMigrated;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration18MigrationConfigKey")
@interface MigrationConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull bookLibrary;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull bookReadingPositions;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC15PRConfiguration19OnboardingConfigKey")
@interface OnboardingConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull supported;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull deferred;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration14OrderConfigKey")
@interface OrderConfigKey : NSObject
@property (nonatomic, readonly, strong) LowCreditsAlertConfigKey * _Nonnull lowCreditsAlert;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration15PRArticleConfig")
@interface PRArticleConfig : NSObject
@property (nonatomic, readonly) BOOL hasSimilars;
@property (nonatomic, readonly) BOOL hasComments;
@property (nonatomic, readonly) BOOL canComment;
@property (nonatomic, readonly) BOOL canShare;
@property (nonatomic, readonly) BOOL canSharePage;
@property (nonatomic, readonly) BOOL hasVotes;
@property (nonatomic, readonly) BOOL isAuthRequiredToListen;
@property (nonatomic, readonly) BOOL isAuthRequiredToPrint;
@property (nonatomic, readonly) BOOL selectBestFrontImage;
@property (nonatomic, readonly) BOOL isHyphenationEnabled;
@property (nonatomic, readonly) BOOL isArticleDetailsPopoverPresentation;
@property (nonatomic, readonly) BOOL isListeningEnabled;
/// current physical limit
@property (nonatomic, readonly) double imageScaleAPILimit;
@property (nonatomic) double imageScaleLimit;
@property (nonatomic, readonly) CGFloat imageScaleThreshold;
@property (nonatomic, readonly) BOOL isLargePreviewForVideoAllowed;
@property (nonatomic, readonly) enum ArticleGalleryCaptionPosition galleryCaptionPosition;
@property (nonatomic, readonly) NSInteger numberOfLinesForPreview;
@property (nonatomic, readonly) NSUInteger detailsViewLightBackgroundColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface PRAuthorizationConfig (SWIFT_EXTENSION(PRConfiguration))
+ (void)registerDependencies;
@end


@interface PRAuthorizationConfig (SWIFT_EXTENSION(PRConfiguration))
@property (nonatomic, readonly) enum AuthorizationType type;
@end


@interface PRConfig (SWIFT_EXTENSION(PRConfiguration))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AdConfig * _Nonnull adConfig;)
+ (AdConfig * _Nonnull)adConfig SWIFT_WARN_UNUSED_RESULT;
@end


@interface PRConfig (SWIFT_EXTENSION(PRConfiguration))
+ (void)registerDependencies;
@end


@interface PRConfig (SWIFT_EXTENSION(PRConfiguration))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ExternalLinkAccountConfig * _Nonnull externalLinkAccountConfig;)
+ (ExternalLinkAccountConfig * _Nonnull)externalLinkAccountConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MigrationConfig * _Nonnull migrationConfig;)
+ (MigrationConfig * _Nonnull)migrationConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ATTConfig * _Nonnull attConfig;)
+ (ATTConfig * _Nonnull)attConfig SWIFT_WARN_UNUSED_RESULT;
@end


@class RadioConfig;
@class SplashScreenConfig;

@interface PRConfig (SWIFT_EXTENSION(PRConfiguration))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL isFullUILoaded;)
+ (BOOL)isFullUILoaded SWIFT_WARN_UNUSED_RESULT;
+ (void)setIsFullUILoaded:(BOOL)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) RadioConfig * _Nonnull radioConfig;)
+ (RadioConfig * _Nonnull)radioConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CancellationAdvisoryConfig * _Nonnull cancellationAdvisoryConfig;)
+ (CancellationAdvisoryConfig * _Nonnull)cancellationAdvisoryConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SplashScreenConfig * _Nonnull splashScreenConfig;)
+ (SplashScreenConfig * _Nonnull)splashScreenConfig SWIFT_WARN_UNUSED_RESULT;
@end

@class RequestSimulation;

@interface PRConfig (SWIFT_EXTENSION(PRConfiguration))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isPremiumEligibleUnconditionally;)
+ (BOOL)isPremiumEligibleUnconditionally SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL userPermissionRequestsDisabled;)
+ (BOOL)userPermissionRequestsDisabled SWIFT_WARN_UNUSED_RESULT;
/// DeliveryQueue methods to be simulated.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) RequestSimulation * _Nonnull dqRequestSimulation;)
+ (RequestSimulation * _Nonnull)dqRequestSimulation SWIFT_WARN_UNUSED_RESULT;
/// Base online service methods to be simulated.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) RequestSimulation * _Nonnull baseRequestSimulation;)
+ (RequestSimulation * _Nonnull)baseRequestSimulation SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL requestCachesDisabled;)
+ (BOOL)requestCachesDisabled SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC15PRConfiguration11PRConfigKey")
@interface PRConfigKey : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull rawValue;
- (nonnull instancetype)initWithRawValue:(NSString * _Nonnull)rawValue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PubHubConfigKey;
@class ReaderConfigKey;
@class SearchConfigKey;
@class SplashScreenConfigKey;

@interface PRConfigKey (SWIFT_EXTENSION(PRConfiguration))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AdConfigKey * _Nonnull ads;)
+ (AdConfigKey * _Nonnull)ads SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AnalyticsConfigKey * _Nonnull analytics;)
+ (AnalyticsConfigKey * _Nonnull)analytics SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AppMenuConfigKey * _Nonnull appMenu;)
+ (AppMenuConfigKey * _Nonnull)appMenu SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ArticleConfigKey * _Nonnull article;)
+ (ArticleConfigKey * _Nonnull)article SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AuthorizationConfigKey * _Nonnull authorization;)
+ (AuthorizationConfigKey * _Nonnull)authorization SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRConfigKey * _Nonnull brandEdition;)
+ (PRConfigKey * _Nonnull)brandEdition SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CancellationAdvisoryConfigKey * _Nonnull cancellationAdvisory;)
+ (CancellationAdvisoryConfigKey * _Nonnull)cancellationAdvisory SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CatalogConfigKey * _Nonnull catalog;)
+ (CatalogConfigKey * _Nonnull)catalog SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CustomerSupportConfigKey * _Nonnull customerSupport;)
+ (CustomerSupportConfigKey * _Nonnull)customerSupport SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRConfigKey * _Nonnull deallocAlertClasses;)
+ (PRConfigKey * _Nonnull)deallocAlertClasses SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRConfigKey * _Nonnull hotspotAllowed;)
+ (PRConfigKey * _Nonnull)hotspotAllowed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LibraryConfigKey * _Nonnull library;)
+ (LibraryConfigKey * _Nonnull)library SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LocalServerConfigKey * _Nonnull localServer;)
+ (LocalServerConfigKey * _Nonnull)localServer SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OnboardingConfigKey * _Nonnull onboarding;)
+ (OnboardingConfigKey * _Nonnull)onboarding SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OrderConfigKey * _Nonnull order;)
+ (OrderConfigKey * _Nonnull)order SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PubHubConfigKey * _Nonnull pubHub;)
+ (PubHubConfigKey * _Nonnull)pubHub SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ReaderConfigKey * _Nonnull reader;)
+ (ReaderConfigKey * _Nonnull)reader SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRConfigKey * _Nonnull rcuEnabled;)
+ (PRConfigKey * _Nonnull)rcuEnabled SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SearchConfigKey * _Nonnull search;)
+ (SearchConfigKey * _Nonnull)search SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SplashScreenConfigKey * _Nonnull splashScreen;)
+ (SplashScreenConfigKey * _Nonnull)splashScreen SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MigrationConfigKey * _Nonnull migration;)
+ (MigrationConfigKey * _Nonnull)migration SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRConfigKey * _Nonnull tooltipsEnabled;)
+ (PRConfigKey * _Nonnull)tooltipsEnabled SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRConfigKey * _Nonnull userPermissionRequestsDisabled;)
+ (PRConfigKey * _Nonnull)userPermissionRequestsDisabled SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRConfigKey * _Nonnull unconditionalPremiumEligibility;)
+ (PRConfigKey * _Nonnull)unconditionalPremiumEligibility SWIFT_WARN_UNUSED_RESULT;
@end


@interface PROrderConfig (SWIFT_EXTENSION(PRConfiguration))
@property (nonatomic, readonly) BOOL typeSpecificTextForDatePicker;
@end


@interface PROrderConfig (SWIFT_EXTENSION(PRConfiguration))
@property (nonatomic, readonly, strong) LowCreditsAlertConfig * _Nonnull lowCredits;
@end



SWIFT_CLASS("_TtC15PRConfiguration15PubHubConfigKey")
@interface PubHubConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull bannersOrder;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration11RadioConfig")
@interface RadioConfig : NSObject
@property (nonatomic, readonly, strong) FeaturedRadioConfig * _Nonnull featured;
@property (nonatomic, readonly) BOOL isEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration12ReaderConfig")
@interface ReaderConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ReaderConfig (SWIFT_EXTENSION(PRConfiguration))
@property (nonatomic, readonly) BOOL hasFavourites;
@property (nonatomic, readonly) BOOL hasBookmarks;
@property (nonatomic, readonly) BOOL hasSmartSearch;
@property (nonatomic, readonly) BOOL isTextViewFlowAllowed;
@property (nonatomic, readonly) BOOL shouldReplicaHideTitle;
@property (nonatomic, readonly) BOOL isTextViewSelectCopyAllowed;
@property (nonatomic, readonly) BOOL nativeSharingSelectedOnly;
@property (nonatomic, readonly) BOOL isDropcapEnabled;
@property (nonatomic, readonly) BOOL isHighligtingEnabled;
@property (nonatomic, readonly) BOOL isSmartZoomEnabled;
@property (nonatomic) BOOL isFullScreenDisabled;
@property (nonatomic, readonly) double barsHidingDelay;
@end


SWIFT_CLASS("_TtC15PRConfiguration15ReaderConfigKey")
@interface ReaderConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull fullScreenDisabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration22ReadingAnalyticsConfig")
@interface ReadingAnalyticsConfig : NSObject
/// Time interval for debouncing of frame change on scrolling
@property (nonatomic, readonly) NSTimeInterval frameDebounce;
/// Minimal time duration of the frame for reporting
@property (nonatomic, readonly) NSTimeInterval frameDurationThreshold;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration25ReadingAnalyticsConfigKey")
@interface ReadingAnalyticsConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull frameDebounce;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull frameDurationThreshold;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSData;

SWIFT_CLASS("_TtC15PRConfiguration17RequestSimulation")
@interface RequestSimulation : NSObject
/// Makes request simulation attempt if corresponding configuration is provided.
- (NSData * _Nullable)responseWithRequest:(NSString * _Nonnull)request method:(NSString * _Nonnull)method SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15PRConfiguration12SearchConfig")
@interface SearchConfig : NSObject
@property (nonatomic, readonly, strong) GlobalSearchConfig * _Nonnull global;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration15SearchConfigKey")
@interface SearchConfigKey : NSObject
@property (nonatomic, readonly, strong) GlobalSearchConfigKey * _Nonnull global;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration18SplashScreenConfig")
@interface SplashScreenConfig : NSObject
@property (nonatomic, readonly) BOOL isPoweredByImageEnabled;
@property (nonatomic, readonly) BOOL isAnimatedLogoEnabled;
@property (nonatomic, readonly) CGFloat animatedLogoProgress;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration21SplashScreenConfigKey")
@interface SplashScreenConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull poweredByImageEnabled;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull animatedLogoEnabled;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull animatedLogoProgress;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration27TreasureDataAnalyticsConfig")
@interface TreasureDataAnalyticsConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable apiKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull database;
@property (nonatomic, readonly, copy) NSString * _Nonnull table;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration30TreasureDataAnalyticsConfigKey")
@interface TreasureDataAnalyticsConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull apiKey;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull database;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull table;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PRConfiguration17UserConsentConfig")
@interface UserConsentConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable privacyPolicyURL;
@property (nonatomic, readonly) BOOL shouldAskForConsent;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
