#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef PRCONFIGURATION_SWIFT_H
#define PRCONFIGURATION_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import PRSyntacticSugar;
@import UIKit;
#endif

#import <PRConfiguration/PRConfiguration.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PRConfiguration",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC15PRConfiguration9ATTConfig")
@interface ATTConfig : NSObject
@property (nonatomic, readonly) BOOL isPermissionRequestEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AccountDeleteConfig;
@class TermsOfUseConfig;
@class DeviceAccountConfig;
SWIFT_CLASS("_TtC15PRConfiguration13AccountConfig")
@interface AccountConfig : NSObject
@property (nonatomic, readonly) BOOL showAccountVCEditBarButton;
@property (nonatomic, readonly) BOOL showAccountChangeEmailPermissionSection;
@property (nonatomic, readonly) BOOL showAccountProductSection;
@property (nonatomic, readonly) BOOL showAccountDetailSection;
@property (nonatomic, readonly) BOOL showAccountVCNicknameRow;
@property (nonatomic, readonly) BOOL showAccountVCServiceName;
@property (nonatomic, readonly, strong, getter=delete) AccountDeleteConfig * _Nonnull delete_;
@property (nonatomic, readonly, strong) TermsOfUseConfig * _Nonnull termsOfUse;
@property (nonatomic, readonly, strong) DeviceAccountConfig * _Nonnull deviceAccount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
SWIFT_CLASS("_TtC15PRConfiguration19AccountDeleteConfig")
@interface AccountDeleteConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable recipientEmail;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AdsType;
SWIFT_CLASS("_TtC15PRConfiguration8AdConfig")
@interface AdConfig : NSObject
@property (nonatomic, readonly) BOOL simulateGoogleAds;
@property (nonatomic, readonly, strong) AdsType * _Nonnull type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PRConfigKey;
SWIFT_CLASS("_TtC15PRConfiguration11AdConfigKey")
@interface AdConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull type;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull googleAdsEnabled;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull htmlAdsEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_RESILIENT_CLASS("_TtC15PRConfiguration7AdsType")
@interface AdsType : _PROptionSet
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AdsType * _Nonnull html;)
+ (AdsType * _Nonnull)html SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AdsType * _Nonnull google;)
+ (AdsType * _Nonnull)google SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithRawValue:(NSInteger)rawValue OBJC_DESIGNATED_INITIALIZER;
@end

@class AnalyticsUserId;
@class MainMenuAnalyticsConfig;
@class ReadingAnalyticsConfig;
@class FirebaseAnalyticsConfig;
@class ComScoreAnalyticsConfig;
@class TreasureDataAnalyticsConfig;
@class MarfeelAnalyticsConfig;
@class SpoorAnalyticsConfig;
SWIFT_CLASS("_TtC15PRConfiguration15AnalyticsConfig")
@interface AnalyticsConfig : NSObject
@property (nonatomic, readonly, strong) AnalyticsUserId * _Nonnull userIdType;
@property (nonatomic, readonly) BOOL replicaPageTrackingEnabled;
@property (nonatomic, readonly, strong) MainMenuAnalyticsConfig * _Nonnull mainMenu;
@property (nonatomic, readonly, strong) ReadingAnalyticsConfig * _Nonnull readingConfig;
@property (nonatomic, readonly, strong) FirebaseAnalyticsConfig * _Nullable firebase;
@property (nonatomic, readonly, strong) ComScoreAnalyticsConfig * _Nullable comScore;
@property (nonatomic, readonly, strong) TreasureDataAnalyticsConfig * _Nullable treasureData;
@property (nonatomic, readonly, strong) MarfeelAnalyticsConfig * _Nullable marfeel;
@property (nonatomic, readonly, strong) SpoorAnalyticsConfig * _Nullable spoor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface AnalyticsConfig (SWIFT_EXTENSION(PRConfiguration))
+ (void)registerDependencies;
@end

@class FirebaseAnalyticsConfigKey;
@class ReadingAnalyticsConfigKey;
@class TreasureDataAnalyticsConfigKey;
@class SpoorAnalyticsConfigKey;
SWIFT_CLASS("_TtC15PRConfiguration18AnalyticsConfigKey")
@interface AnalyticsConfigKey : NSObject
@property (nonatomic, readonly, strong) FirebaseAnalyticsConfigKey * _Nonnull firebase;
@property (nonatomic, readonly, strong) ReadingAnalyticsConfigKey * _Nonnull reading;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull userIdType;
@property (nonatomic, readonly, strong) TreasureDataAnalyticsConfigKey * _Nonnull treasureData;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull replicaPageTrackingDisabled;
@property (nonatomic, readonly, strong) SpoorAnalyticsConfigKey * _Nonnull spoor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_RESILIENT_CLASS("_TtC15PRConfiguration15AnalyticsUserId")
@interface AnalyticsUserId : _PROptionSet
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AnalyticsUserId * _Nonnull accountNumber;)
+ (AnalyticsUserId * _Nonnull)accountNumber SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AnalyticsUserId * _Nonnull internalRefNumber;)
+ (AnalyticsUserId * _Nonnull)internalRefNumber SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithRawValue:(NSInteger)rawValue OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration13AppInfoConfig")
@interface AppInfoConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable appId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration13AppMenuConfig")
@interface AppMenuConfig : NSObject
/// In case of branded item opens a special screen for BE apps instead of default more popup
@property (nonatomic, readonly) BOOL showMoreItemsInPopUp;
@property (nonatomic, readonly) PRAppMenuItemAbsence absence;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration16AppMenuConfigKey")
@interface AppMenuConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull catalogPanelMode;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull initialPanel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration19ArticleBylineConfig")
@interface ArticleBylineConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration16ArticleConfigKey")
@interface ArticleConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull numberOfLinesForPreview;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull previewTextDarkColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration41ArticleDetailsPreferredImageCaptionConfig")
@interface ArticleDetailsPreferredImageCaptionConfig : NSObject
@property (nonatomic, readonly) NSInteger numberOfLines;
@property (nonatomic, readonly) NSTextAlignment alignment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration34ArticleDetailsPreferredImageConfig")
@interface ArticleDetailsPreferredImageConfig : NSObject
@property (nonatomic, readonly, strong) ArticleDetailsPreferredImageCaptionConfig * _Nonnull caption;
@property (nonatomic, readonly) BOOL largeLayoutEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration25ArticleDetailsTitleConfig")
@interface ArticleDetailsTitleConfig : NSObject
@property (nonatomic, readonly) NSTextAlignment textAlignment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration24ArticleDetailsViewConfig")
@interface ArticleDetailsViewConfig : NSObject
@property (nonatomic, readonly, strong) ArticleDetailsPreferredImageConfig * _Nonnull preferredImage;
@property (nonatomic, readonly, strong) ArticleDetailsTitleConfig * _Nonnull title;
@property (nonatomic, readonly) NSUInteger lightBackgroundColor;
@property (nonatomic, readonly) NSTextAlignment textAlignment;
@property (nonatomic, readonly) BOOL presentInPopover;
@property (nonatomic, readonly) BOOL presentRadioOnTop;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ArticlePreviewFontConfig;
@class Font;
SWIFT_CLASS("_TtC15PRConfiguration17ArticleFontConfig")
@interface ArticleFontConfig : NSObject
@property (nonatomic, readonly, strong) ArticlePreviewFontConfig * _Nonnull preview;
@property (nonatomic, readonly, strong) Font * _Nullable caption;
@property (nonatomic, readonly, strong) Font * _Nullable title;
@property (nonatomic, readonly, strong) Font * _Nonnull subtitle;
@property (nonatomic, readonly, strong) Font * _Nullable byline;
@property (nonatomic, readonly, strong) Font * _Nonnull body;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ArticleGalleryCaptionPosition, open) {
  ArticleGalleryCaptionPositionAutomatic = 0,
  ArticleGalleryCaptionPositionUnderImage = 1,
};

SWIFT_CLASS("_TtC15PRConfiguration24ArticlePreviewFontConfig")
@interface ArticlePreviewFontConfig : NSObject
@property (nonatomic, readonly, strong) Font * _Nullable body;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration17GlobalPrintConfig")
@interface GlobalPrintConfig : NSObject
@property (nonatomic, readonly) BOOL isEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration18ArticlePrintConfig")
@interface ArticlePrintConfig : GlobalPrintConfig
@property (nonatomic, readonly) BOOL isEnabled;
@property (nonatomic, readonly) BOOL isGraphicsEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration20ArticleRelatedConfig")
@interface ArticleRelatedConfig : NSObject
@property (nonatomic, readonly) BOOL enabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration17ArticleTagsConfig")
@interface ArticleTagsConfig : NSObject
@property (nonatomic, readonly) BOOL enabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration11Auth0Config")
@interface Auth0Config : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration22AuthorizationConfigKey")
@interface AuthorizationConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull type;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull frequency;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull frequencyDays;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull cleanWebView;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull externalAuthType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, AuthorizationType, open) {
  AuthorizationTypeOptional = 0,
  AuthorizationTypeMandatory = 1,
};

SWIFT_CLASS("_TtC15PRConfiguration10BookConfig")
@interface BookConfig : NSObject
@property (nonatomic, readonly) Class _Nullable ePubReader;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration16BookReaderConfig")
@interface BookReaderConfig : NSObject
@property (nonatomic, readonly) NSInteger locationDivider;
@property (nonatomic, readonly) NSInteger defaultFontSize;
@property (nonatomic, readonly) BOOL isCopyButtonAvailable;
@property (nonatomic, readonly) NSInteger maxWordsInSelectionForLookup;
@property (nonatomic, readonly) BOOL isTextSpacingAvailable;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface NSBundle (SWIFT_EXTENSION(PRConfiguration))
@property (nonatomic, readonly, copy) NSString * _Nonnull version;
@property (nonatomic, readonly, copy) NSString * _Nonnull shortVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull extendedVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull conditionalVersion;
@property (nonatomic, readonly, copy) NSString * _Nullable identifier;
@property (nonatomic, readonly, copy) NSString * _Nullable displayName;
@end

SWIFT_CLASS("_TtC15PRConfiguration26CancellationAdvisoryConfig")
@interface CancellationAdvisoryConfig : NSObject
@property (nonatomic, readonly) BOOL isEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration29CancellationAdvisoryConfigKey")
@interface CancellationAdvisoryConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull enabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration16CatalogConfigKey")
@interface CatalogConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull presscatalogUpdateDisabled;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull thumbnailStretchingEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration23ComScoreAnalyticsConfig")
@interface ComScoreAnalyticsConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable publisherId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration6Config")
@interface Config : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration14CoreDataConfig")
@interface CoreDataConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull storeType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration21CustomerSupportConfig")
@interface CustomerSupportConfig : NSObject
@property (nonatomic, readonly) BOOL show;
@property (nonatomic, readonly, copy) NSString * _Nonnull email;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable emails;
@property (nonatomic, readonly, copy) NSString * _Nullable phone;
@property (nonatomic, readonly, copy) NSString * _Nullable cookiePolicyURL;
@property (nonatomic, readonly, copy) NSString * _Nullable privacyPolicyURL;
@property (nonatomic, readonly, copy) NSString * _Nullable termsOfUseURL;
@property (nonatomic, readonly, copy) NSString * _Nonnull manageSubscriptionURL;
@property (nonatomic, readonly) BOOL hideFeedbackEmailQuestion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration24CustomerSupportConfigKey")
@interface CustomerSupportConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull show;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull email;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull emails;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull phone;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull privacyPolicyURL;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull termsOfUseURL;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull cookiePolicyURL;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull manageSubscriptionURL;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull hideFeedbackEmailQuestion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration19DeviceAccountConfig")
@interface DeviceAccountConfig : NSObject
@property (nonatomic, readonly) BOOL bookmarksEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURL;
SWIFT_CLASS("_TtC15PRConfiguration31DirectExternalLinkAccountConfig")
@interface DirectExternalLinkAccountConfig : NSObject
@property (nonatomic, readonly) BOOL isEnabled;
@property (nonatomic, readonly, copy) NSURL * _Nullable link;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ExternalAuthType, open) {
  ExternalAuthTypeWebView = 0,
  ExternalAuthTypeWebSession = 1,
  ExternalAuthTypeSafari = 2,
};

SWIFT_CLASS("_TtC15PRConfiguration25ExternalLinkAccountConfig")
@interface ExternalLinkAccountConfig : NSObject
@property (nonatomic, readonly) BOOL isEnabled;
@property (nonatomic, readonly, copy) NSString * _Nonnull developerName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration14FacebookConfig")
@interface FacebookConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration19FeaturedRadioConfig")
@interface FeaturedRadioConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_RESILIENT_CLASS("_TtC15PRConfiguration14FeedNavigation")
@interface FeedNavigation : _PROptionSet
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FeedNavigation * _Nonnull button;)
+ (FeedNavigation * _Nonnull)button SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) FeedNavigation * _Nonnull tabs;)
+ (FeedNavigation * _Nonnull)tabs SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithRawValue:(NSInteger)rawValue OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration23FirebaseAnalyticsConfig")
@interface FirebaseAnalyticsConfig : NSObject
@property (nonatomic, readonly) BOOL isAnalyticsEnabled;
@property (nonatomic, readonly) BOOL isPushEnabled;
@property (nonatomic, readonly, copy) NSString * _Nullable userIdKey;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration26FirebaseAnalyticsConfigKey")
@interface FirebaseAnalyticsConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull userIdKey;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration4Font")
@interface Font : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull fileName;
@property (nonatomic, readonly) double pointSizeCorrection;
- (nonnull instancetype)initWithFileName:(NSString * _Nonnull)fileName pointSizeCorrection:(double)pointSizeCorrection OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15PRConfiguration10FontConfig")
@interface FontConfig : NSObject
@property (nonatomic, readonly) BOOL isFontSwizzlingEnabled;
@property (nonatomic, readonly, strong) ArticleFontConfig * _Nullable article;
@property (nonatomic, readonly, copy) NSString * _Nullable mainFont;
@property (nonatomic, readonly, copy) NSString * _Nullable mainBoldFont;
@property (nonatomic, readonly, copy) NSString * _Nullable secondaryFont;
@property (nonatomic, readonly, copy) NSString * _Nullable secondaryBoldFont;
@property (nonatomic, readonly, strong) Font * _Nullable feedSection;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface FontConfig (SWIFT_EXTENSION(PRConfiguration))
+ (void)registerDependencies;
@end

SWIFT_CLASS("_TtC15PRConfiguration18GlobalSearchConfig")
@interface GlobalSearchConfig : NSObject
@property (nonatomic, readonly) BOOL isEnabled;
@property (nonatomic, readonly) BOOL isOngoingStoriesSearchEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration21GlobalSearchConfigKey")
@interface GlobalSearchConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull enabled;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull isOngoingStoriesSearchEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration12GoogleConfig")
@interface GoogleConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class HomeSourcesConfig;
@class HomeFeedConfig;
SWIFT_CLASS("_TtC15PRConfiguration10HomeConfig")
@interface HomeConfig : NSObject
@property (nonatomic, readonly, strong) HomeSourcesConfig * _Nonnull sources;
@property (nonatomic, readonly, strong) HomeFeedConfig * _Nonnull feed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class RelatedArticlesConfig;
SWIFT_CLASS("_TtC15PRConfiguration14HomeFeedConfig")
@interface HomeFeedConfig : NSObject
@property (nonatomic, readonly, strong) FeedNavigation * _Nonnull navigation;
@property (nonatomic, readonly, strong) RelatedArticlesConfig * _Nonnull relatedArticles;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration17HomeSourcesConfig")
@interface HomeSourcesConfig : NSObject
@property (nonatomic, readonly) BOOL displayFavoriteIssues;
@property (nonatomic, readonly) BOOL isDisabled;
@property (nonatomic, readonly) NSInteger issueAmount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class HotSpotNotificationsConfig;
SWIFT_CLASS("_TtC15PRConfiguration13HotSpotConfig")
@interface HotSpotConfig : NSObject
@property (nonatomic, readonly) BOOL isEnabled;
@property (nonatomic, readonly) BOOL isMapEnabled;
@property (nonatomic, readonly) BOOL isCupButtonEnabled;
@property (nonatomic, readonly) BOOL isOptOut;
@property (nonatomic, readonly, copy) NSString * _Nonnull proximityUUID;
@property (nonatomic, readonly) BOOL isGeoFencingEnabled;
@property (nonatomic, readonly, strong) HotSpotNotificationsConfig * _Nonnull notifications;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class HotSpotLocalNotificationsConfig;
@class HotSpotWelcomeNotificationsConfig;
SWIFT_CLASS_NAMED("NotificationsConfig")
@interface HotSpotNotificationsConfig : NSObject
@property (nonatomic, readonly, strong) HotSpotLocalNotificationsConfig * _Nonnull local;
@property (nonatomic, readonly, strong) HotSpotWelcomeNotificationsConfig * _Nonnull welcome;
@property (nonatomic, readonly) BOOL isEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("LocalConfig")
@interface HotSpotLocalNotificationsConfig : NSObject
@property (nonatomic, readonly) NSTimeInterval timeInterval;
@property (nonatomic, readonly) NSTimeInterval requestReminderTimeInterval;
@property (nonatomic, readonly) BOOL showOnSwitch;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("WelcomeConfig")
@interface HotSpotWelcomeNotificationsConfig : NSObject
@property (nonatomic, readonly) NSTimeInterval timeInterval;
@property (nonatomic, readonly) BOOL showOnSwitch;
@property (nonatomic, readonly) BOOL showOnStart;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration9IAPConfig")
@interface IAPConfig : NSObject
@property (nonatomic, readonly) BOOL isSaveMoneyTextEnabled;
@property (nonatomic, readonly) BOOL decodeReceiptsLocaly;
@property (nonatomic, readonly) BOOL isSelectProductEnabled;
@property (nonatomic, readonly) BOOL isAccountRequired;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration13LibraryConfig")
@interface LibraryConfig : NSObject
@property (nonatomic, readonly) BOOL renewableIssueLicense;
@property (nonatomic, readonly) BOOL keepExpiredItems;
/// Number of seconds book content is available to read in offline mode AFTER it was opened offline first time.
/// <code>Default value</code> : 2 weeks (1209600 seconds)
@property (nonatomic, readonly) NSTimeInterval bookOfflineAccessPeriod;
@property (nonatomic, readonly, copy) NSString * _Nonnull myLibraryTitleStringKey;
@property (nonatomic, readonly) BOOL modernFeedAPIEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration16LibraryConfigKey")
@interface LibraryConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull bookOfflineAccessPeriod;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull keepExpiredItems;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull renewableIssueLicense;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull myLibraryTitleStringKey;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull modernFeedAPIEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration17LocalServerConfig")
@interface LocalServerConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable serverURL;
@property (nonatomic, readonly) BOOL cleanDownloadedContentAfterDeauthorization;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration20LocalServerConfigKey")
@interface LocalServerConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull serverURL;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull cleanDownloadedContentAfterDeauthorization;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration16LowCreditsConfig")
@interface LowCreditsConfig : Config
@property (nonatomic, readonly) NSTimeInterval alertReappearanceTimeInterval;
@property (nonatomic, readonly) BOOL isAdviceEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration19LowCreditsConfigKey")
@interface LowCreditsConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull alertReappearanceTimeInterval;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull noticeEnabled;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull adviceEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration23MainMenuAnalyticsConfig")
@interface MainMenuAnalyticsConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable forYouValue;
@property (nonatomic, readonly, copy) NSString * _Nullable browseValue;
@property (nonatomic, readonly, copy) NSString * _Nullable downloadedValue;
@property (nonatomic, readonly, copy) NSString * _Nullable accountsValue;
@property (nonatomic, readonly, copy) NSString * _Nullable aboutUsValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration22MarfeelAnalyticsConfig")
@interface MarfeelAnalyticsConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration15MigrationConfig")
@interface MigrationConfig : NSObject
@property (nonatomic) BOOL bookLibraryMigrated;
@property (nonatomic) BOOL bookReadingPositionsMigrated;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration18MigrationConfigKey")
@interface MigrationConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull bookLibrary;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull bookReadingPositions;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface NSLocale (SWIFT_EXTENSION(PRConfiguration))
- (NSString * _Nullable)languageNameWithIsoCode:(NSString * _Nonnull)isoCode SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)hasCountryForLocaleIdentifier:(NSString * _Nonnull)localeIdentifier SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)languageAndScriptFromLocaleIdentifier:(NSString * _Nonnull)localeIdentifier SWIFT_WARN_UNUSED_RESULT;
/// based on provided combination of language-script-country
/// gives valid language id (locale code) for langauge region variation
/// dropping country if corresponding combination could not produce valid language id
/// Examples:
/// en-US -> en-US
/// ru-CA -> ru
/// zh-Hant-HK -> zh-Hant-HK
/// zh-Hans-US -> zh-Hans
+ (NSString * _Nonnull)canonicalValidatedLanguageIdentifierFromComponents:(NSDictionary<NSString *, NSString *> * _Nonnull)components SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)canonicalValidatedLanguageIdentifierFrom:(NSString * _Nonnull)localeIdentifier SWIFT_WARN_UNUSED_RESULT;
/// return validated first preferred language identifier or otherwise validated current locale langauge identifier
+ (NSString * _Nonnull)validatedCurrentLanguageIdentifier SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)currentLanguageAndScriptIdentifier SWIFT_WARN_UNUSED_RESULT;
/// return validated language identifiers for all preferred language/countries
+ (NSArray<NSString *> * _Nonnull)validatedPreferredLanguageIdentifiers SWIFT_WARN_UNUSED_RESULT;
/// return validated language identifier for the first found preferred language matching providerd language identifier (usually just langague or language+script for Chinese)
/// essentially adding country to such combination
+ (NSString * _Nullable)validatedPreferredLanguageIdentifierMatching:(NSString * _Nonnull)languageIdentifier SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)validatedLanguageIdentifierWithLanguageCode:(NSString * _Nonnull)languageCode countryCode:(NSString * _Nullable)countryCode SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull validatedLanguageIdentifier;
@end

SWIFT_CLASS("_TtC15PRConfiguration12OAuth2Config")
@interface OAuth2Config : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration19OnboardingConfigKey")
@interface OnboardingConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull supported;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull deferred;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull showTrialSubscriptionIntro;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull signInDisabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration14OrderConfigKey")
@interface OrderConfigKey : NSObject
@property (nonatomic, readonly, strong) LowCreditsConfigKey * _Nonnull lowCredits;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull followDisabled;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull hidePrimiumButton;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull shouldSendAnalyticsEventForPremiumAvailable;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration15PRArticleConfig")
@interface PRArticleConfig : NSObject
@property (nonatomic, readonly, strong) ArticleTagsConfig * _Nonnull tags;
@property (nonatomic, readonly, strong) ArticleRelatedConfig * _Nonnull related;
@property (nonatomic, readonly, strong) ArticleDetailsViewConfig * _Nonnull details;
@property (nonatomic, readonly, strong) ArticleBylineConfig * _Nonnull byline;
@property (nonatomic, readonly) BOOL hasSimilars;
@property (nonatomic, readonly) BOOL hasComments;
@property (nonatomic, readonly) BOOL canComment;
@property (nonatomic, readonly) BOOL hasVotes;
@property (nonatomic, readonly) BOOL isAuthRequiredToListen;
@property (nonatomic, readonly) BOOL isAuthRequiredToPrint;
@property (nonatomic, readonly) BOOL selectBestFrontImage;
@property (nonatomic, readonly) BOOL isHyphenationEnabled;
@property (nonatomic, readonly) BOOL isListeningEnabled;
/// current physical limit
@property (nonatomic, readonly) double imageScaleAPILimit;
@property (nonatomic) double imageScaleLimit;
@property (nonatomic, readonly) CGFloat imageScaleThreshold;
@property (nonatomic, readonly) BOOL isLargePreviewForVideoAllowed;
@property (nonatomic, readonly) enum ArticleGalleryCaptionPosition galleryCaptionPosition;
@property (nonatomic, readonly) NSInteger numberOfLinesForPreview;
@property (nonatomic, readonly) BOOL mastheadEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface PRAuthorizationConfig (SWIFT_EXTENSION(PRConfiguration))
+ (void)registerDependencies;
@end

@interface PRAuthorizationConfig (SWIFT_EXTENSION(PRConfiguration))
@property (nonatomic, readonly) enum AuthorizationType type;
@property (nonatomic, readonly) BOOL cleanWebView;
@property (nonatomic, readonly) enum ExternalAuthType externalAuthType;
@end

@interface PRCatalogConfig (SWIFT_EXTENSION(PRConfiguration))
@property (nonatomic, readonly, strong) BookConfig * _Nullable books;
@property (nonatomic, readonly) NSInteger localPromotionsCount;
@property (nonatomic, readonly) BOOL isFreeIndicatorEnabled;
@end

typedef SWIFT_ENUM(NSInteger, PRCatalogSectionType, open) {
  PRCatalogSectionTypeBegin = -2,
  PRCatalogSectionTypeNone = -1,
  PRCatalogSectionTypeFeatured = 0,
  PRCatalogSectionTypeFilters = 1,
  PRCatalogSectionTypeListen = 2,
  PRCatalogSectionTypeFavorites = 3,
  PRCatalogSectionTypeRecentlyRead = 4,
  PRCatalogSectionTypeLinkedService = 5,
  PRCatalogSectionTypeTopMagazines = 6,
  PRCatalogSectionTypeTopNewspapers = 7,
  PRCatalogSectionTypeBooks = 8,
  PRCatalogSectionTypeJustAdded = 9,
  PRCatalogSectionTypeNewReleases = 10,
  PRCatalogSectionTypeTopFree = 11,
  PRCatalogSectionTypeDownloaded = 12,
  PRCatalogSectionTypeLatestIssues = 13,
  PRCatalogSectionTypeBannerBegin = 14,
  PRCatalogSectionTypeBannerHotspotServices = 15,
  PRCatalogSectionTypeBannerPremiumSubscription = 16,
  PRCatalogSectionTypeBannerImproveExperience = 17,
  PRCatalogSectionTypeBannerPersonalizationCompleted = 18,
  PRCatalogSectionTypeBannerBooks = 19,
  PRCatalogSectionTypeBannerBrazeContentCard = 20,
  PRCatalogSectionTypeBannerAll = 21,
  PRCatalogSectionTypeBannerEnd = 22,
  PRCatalogSectionTypeCategories = 23,
  PRCatalogSectionTypeFullCatalog = 24,
  PRCatalogSectionTypeCategoryContent = 25,
/// Special categories for custom catalog. Might support rows in the future.
  PRCatalogSectionTypeSections = 26,
  PRCatalogSectionTypeHotSpot = 27,
  PRCatalogSectionTypeLatestPublishDay = 28,
  PRCatalogSectionTypeTopAdBanner = 29,
  PRCatalogSectionTypeInlineAdBanner = 30,
  PRCatalogSectionTypeCoBrandingBanner = 31,
  PRCatalogSectionTypeEnd = 32,
};

@interface PRConfig (SWIFT_EXTENSION(PRConfiguration))
+ (void)refresh;
@end

@interface PRConfig (SWIFT_EXTENSION(PRConfiguration))
+ (void)registerDependencies;
@end

@class ShareConfig;
@interface PRConfig (SWIFT_EXTENSION(PRConfiguration))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AdConfig * _Nullable adConfig;)
+ (AdConfig * _Nullable)adConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ShareConfig * _Nullable shareConfig;)
+ (ShareConfig * _Nullable)shareConfig SWIFT_WARN_UNUSED_RESULT;
@end

@class RadioConfig;
@class SplashScreenConfig;
@interface PRConfig (SWIFT_EXTENSION(PRConfiguration))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL isFullUILoaded;)
+ (BOOL)isFullUILoaded SWIFT_WARN_UNUSED_RESULT;
+ (void)setIsFullUILoaded:(BOOL)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) RadioConfig * _Nullable radioConfig;)
+ (RadioConfig * _Nullable)radioConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CancellationAdvisoryConfig * _Nullable cancellationAdvisoryConfig;)
+ (CancellationAdvisoryConfig * _Nullable)cancellationAdvisoryConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SplashScreenConfig * _Nullable splashScreenConfig;)
+ (SplashScreenConfig * _Nullable)splashScreenConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BookReaderConfig * _Nullable bookReaderConfig;)
+ (BookReaderConfig * _Nullable)bookReaderConfig SWIFT_WARN_UNUSED_RESULT;
@end

@class RequestSimulation;
@interface PRConfig (SWIFT_EXTENSION(PRConfiguration))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isPremiumEligibleUnconditionally;)
+ (BOOL)isPremiumEligibleUnconditionally SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL userPermissionRequestsDisabled;)
+ (BOOL)userPermissionRequestsDisabled SWIFT_WARN_UNUSED_RESULT;
/// DeliveryQueue methods to be simulated.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) RequestSimulation * _Nonnull dqRequestSimulation;)
+ (RequestSimulation * _Nonnull)dqRequestSimulation SWIFT_WARN_UNUSED_RESULT;
/// Base online service methods to be simulated.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) RequestSimulation * _Nonnull baseRequestSimulation;)
+ (RequestSimulation * _Nonnull)baseRequestSimulation SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL requestCachesDisabled;)
+ (BOOL)requestCachesDisabled SWIFT_WARN_UNUSED_RESULT;
@end

@class PrintConfig;
@interface PRConfig (SWIFT_EXTENSION(PRConfiguration))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ExternalLinkAccountConfig * _Nullable externalLinkAccountConfig;)
+ (ExternalLinkAccountConfig * _Nullable)externalLinkAccountConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MigrationConfig * _Nullable migrationConfig;)
+ (MigrationConfig * _Nullable)migrationConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ATTConfig * _Nullable attConfig;)
+ (ATTConfig * _Nullable)attConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PrintConfig * _Nullable printConfig;)
+ (PrintConfig * _Nullable)printConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AccountConfig * _Nullable accountConfig;)
+ (AccountConfig * _Nullable)accountConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HotSpotConfig * _Nullable hotSpotConfig;)
+ (HotSpotConfig * _Nullable)hotSpotConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) AppInfoConfig * _Nonnull appInfoConfig;)
+ (AppInfoConfig * _Nonnull)appInfoConfig SWIFT_WARN_UNUSED_RESULT;
+ (void)setAppInfoConfig:(AppInfoConfig * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DirectExternalLinkAccountConfig * _Nonnull directExternalLinkAccountConfig;)
+ (DirectExternalLinkAccountConfig * _Nonnull)directExternalLinkAccountConfig SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL showTestServer;)
+ (BOOL)showTestServer SWIFT_WARN_UNUSED_RESULT;
+ (void)setShowTestServer:(BOOL)newValue;
@end

SWIFT_CLASS("_TtC15PRConfiguration11PRConfigKey")
@interface PRConfigKey : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull rawValue;
- (nonnull instancetype)initWithRawValue:(NSString * _Nonnull)rawValue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PubHubConfigKey;
@class ReaderConfigKey;
@class SearchConfigKey;
@class SplashScreenConfigKey;
@interface PRConfigKey (SWIFT_EXTENSION(PRConfiguration))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AdConfigKey * _Nonnull ads;)
+ (AdConfigKey * _Nonnull)ads SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AnalyticsConfigKey * _Nonnull analytics;)
+ (AnalyticsConfigKey * _Nonnull)analytics SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AppMenuConfigKey * _Nonnull appMenu;)
+ (AppMenuConfigKey * _Nonnull)appMenu SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ArticleConfigKey * _Nonnull article;)
+ (ArticleConfigKey * _Nonnull)article SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AuthorizationConfigKey * _Nonnull authorization;)
+ (AuthorizationConfigKey * _Nonnull)authorization SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRConfigKey * _Nonnull brandEdition;)
+ (PRConfigKey * _Nonnull)brandEdition SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CancellationAdvisoryConfigKey * _Nonnull cancellationAdvisory;)
+ (CancellationAdvisoryConfigKey * _Nonnull)cancellationAdvisory SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CatalogConfigKey * _Nonnull catalog;)
+ (CatalogConfigKey * _Nonnull)catalog SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CustomerSupportConfigKey * _Nonnull customerSupport;)
+ (CustomerSupportConfigKey * _Nonnull)customerSupport SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRConfigKey * _Nonnull deallocAlertClasses;)
+ (PRConfigKey * _Nonnull)deallocAlertClasses SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LibraryConfigKey * _Nonnull library;)
+ (LibraryConfigKey * _Nonnull)library SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LocalServerConfigKey * _Nonnull localServer;)
+ (LocalServerConfigKey * _Nonnull)localServer SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OnboardingConfigKey * _Nonnull onboarding;)
+ (OnboardingConfigKey * _Nonnull)onboarding SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OrderConfigKey * _Nonnull order;)
+ (OrderConfigKey * _Nonnull)order SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PubHubConfigKey * _Nonnull pubHub;)
+ (PubHubConfigKey * _Nonnull)pubHub SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ReaderConfigKey * _Nonnull reader;)
+ (ReaderConfigKey * _Nonnull)reader SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRConfigKey * _Nonnull rcuEnabled;)
+ (PRConfigKey * _Nonnull)rcuEnabled SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SearchConfigKey * _Nonnull search;)
+ (SearchConfigKey * _Nonnull)search SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SplashScreenConfigKey * _Nonnull splashScreen;)
+ (SplashScreenConfigKey * _Nonnull)splashScreen SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MigrationConfigKey * _Nonnull migration;)
+ (MigrationConfigKey * _Nonnull)migration SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRConfigKey * _Nonnull tooltipsEnabled;)
+ (PRConfigKey * _Nonnull)tooltipsEnabled SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRConfigKey * _Nonnull userPermissionRequestsDisabled;)
+ (PRConfigKey * _Nonnull)userPermissionRequestsDisabled SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRConfigKey * _Nonnull unconditionalPremiumEligibility;)
+ (PRConfigKey * _Nonnull)unconditionalPremiumEligibility SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRConfigKey * _Nonnull serviceErrorAlertDisabled;)
+ (PRConfigKey * _Nonnull)serviceErrorAlertDisabled SWIFT_WARN_UNUSED_RESULT;
@end

@interface PROnboardingConfig (SWIFT_EXTENSION(PRConfiguration))
@property (nonatomic, readonly) BOOL showTrialSubscriptionIntro;
@property (nonatomic, readonly) BOOL isSignInDisabled;
@property (nonatomic, readonly) BOOL isPublicationSearchEnabled;
@end

@interface PROrderConfig (SWIFT_EXTENSION(PRConfiguration))
@property (nonatomic, readonly) BOOL typeSpecificTextForDatePicker;
@end

@interface PROrderConfig (SWIFT_EXTENSION(PRConfiguration))
@property (nonatomic, readonly, strong) LowCreditsConfig * _Nullable lowCredits;
@property (nonatomic, readonly) BOOL isFollowEnabled;
@property (nonatomic, readonly) BOOL hidePremiumButton;
@property (nonatomic, readonly) BOOL shouldSendAnalyticsEventForPremiumAvailable;
@end

SWIFT_CLASS("_TtC15PRConfiguration15PagePrintConfig")
@interface PagePrintConfig : GlobalPrintConfig
@property (nonatomic, readonly) BOOL isEnabled;
@property (nonatomic, readonly) NSInteger limitPerIssue;
@property (nonatomic, readonly) BOOL useBitmap;
@property (nonatomic, readonly) CGFloat bitmapScale;
@property (nonatomic, readonly) BOOL isUnlimited;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration11PrintConfig")
@interface PrintConfig : GlobalPrintConfig
@property (nonatomic, readonly, strong) PagePrintConfig * _Nonnull page;
@property (nonatomic, readonly, strong) ArticlePrintConfig * _Nonnull article;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration15PubHubConfigKey")
@interface PubHubConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull bannersOrder;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration11RadioConfig")
@interface RadioConfig : NSObject
@property (nonatomic, readonly, strong) FeaturedRadioConfig * _Nullable featured;
@property (nonatomic, readonly) BOOL isEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration12ReaderConfig")
@interface ReaderConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface ReaderConfig (SWIFT_EXTENSION(PRConfiguration))
@property (nonatomic, readonly) BOOL hasFavourites;
@property (nonatomic, readonly) BOOL hasBookmarks;
@property (nonatomic, readonly) BOOL hasSmartSearch;
@property (nonatomic, readonly) BOOL isTextViewFlowAllowed;
@property (nonatomic, readonly) BOOL shouldReplicaHideTitle;
@property (nonatomic, readonly) BOOL isTextViewSelectCopyAllowed;
@property (nonatomic, readonly) BOOL nativeSharingSelectedOnly;
@property (nonatomic, readonly) BOOL isDropcapEnabled;
@property (nonatomic, readonly) BOOL isHighligtingEnabled;
@property (nonatomic, readonly) BOOL isSmartZoomEnabled;
@property (nonatomic) BOOL isFullScreenDisabled;
@property (nonatomic, readonly) double barsHidingDelay;
@property (nonatomic, readonly) BOOL externalLinksEnabled;
@end

SWIFT_CLASS("_TtC15PRConfiguration15ReaderConfigKey")
@interface ReaderConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull fullScreenDisabled;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull externalLinksEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration22ReadingAnalyticsConfig")
@interface ReadingAnalyticsConfig : NSObject
/// Time interval for debouncing of frame change on scrolling
@property (nonatomic, readonly) NSTimeInterval frameDebounce;
/// Minimal time duration of the frame for reporting
@property (nonatomic, readonly) NSTimeInterval frameDurationThreshold;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration25ReadingAnalyticsConfigKey")
@interface ReadingAnalyticsConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull frameDebounce;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull frameDurationThreshold;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration21RelatedArticlesConfig")
@interface RelatedArticlesConfig : NSObject
@property (nonatomic, readonly) BOOL thumbnailsEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSData;
SWIFT_CLASS("_TtC15PRConfiguration17RequestSimulation")
@interface RequestSimulation : NSObject
/// Makes request simulation attempt if corresponding configuration is provided.
- (NSData * _Nullable)responseWithRequest:(NSString * _Nonnull)request method:(NSString * _Nonnull)method SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15PRConfiguration12SearchConfig")
@interface SearchConfig : NSObject
@property (nonatomic, readonly, strong) GlobalSearchConfig * _Nullable global;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration15SearchConfigKey")
@interface SearchConfigKey : NSObject
@property (nonatomic, readonly, strong) GlobalSearchConfigKey * _Nonnull global;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration11ShareConfig")
@interface ShareConfig : NSObject
@property (nonatomic, readonly) BOOL isEnabled;
@property (nonatomic, readonly) BOOL isArticleEnabled;
@property (nonatomic, readonly) BOOL isPageEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration30SplashScreenAnimatedLogoConfig")
@interface SplashScreenAnimatedLogoConfig : NSObject
@property (nonatomic, readonly) BOOL isEnabled;
@property (nonatomic, readonly) BOOL isSpecial;
@property (nonatomic, readonly) CGFloat progress;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration18SplashScreenConfig")
@interface SplashScreenConfig : NSObject
@property (nonatomic, readonly) BOOL isPoweredByImageEnabled;
@property (nonatomic, strong) SplashScreenAnimatedLogoConfig * _Nonnull animatedLogo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration21SplashScreenConfigKey")
@interface SplashScreenConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull poweredByImageEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration20SpoorAnalyticsConfig")
@interface SpoorAnalyticsConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration23SpoorAnalyticsConfigKey")
@interface SpoorAnalyticsConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull baseUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration16TermsOfUseConfig")
@interface TermsOfUseConfig : NSObject
@property (nonatomic, readonly) BOOL isUserConfirmationRequired;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration27TreasureDataAnalyticsConfig")
@interface TreasureDataAnalyticsConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable apiKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull database;
@property (nonatomic, readonly, copy) NSString * _Nonnull table;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration30TreasureDataAnalyticsConfigKey")
@interface TreasureDataAnalyticsConfigKey : NSObject
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull apiKey;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull database;
@property (nonatomic, readonly, strong) PRConfigKey * _Nonnull table;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC15PRConfiguration17UserConsentConfig")
@interface UserConsentConfig : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable privacyPolicyURL;
@property (nonatomic, readonly) BOOL shouldAskForConsent;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface NSUserDefaults (SWIFT_EXTENSION(PRConfiguration))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSUserDefaults * _Nullable sharedUserDefaults;)
+ (NSUserDefaults * _Nullable)sharedUserDefaults SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSString * _Nullable accessToken;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable baseServices;
@end

SWIFT_CLASS("_TtC15PRConfiguration24UserInterfaceStyleConfig")
@interface UserInterfaceStyleConfig : Config
@property (nonatomic, readonly) BOOL isUIStyleSelectionEnabled;
@property (nonatomic) BOOL isTextFlowStyleSelectionEnabled;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
