#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1 effective-5.10 (swiftlang-6.1.0.110.21 clang-1700.0.13.3)
#ifndef PRUIKIT_SWIFT_H
#define PRUIKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import MBProgressHUD;
@import ObjectiveC;
@import PRSyntacticSugar;
@import QuartzCore;
@import UIKit;
@import WebKit;
#endif

#import <PRUIKit/PRUIKit.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PRUIKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSCoder;
SWIFT_CLASS("_TtC7PRUIKit16ActionButtonView")
@interface ActionButtonView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)safeAreaInsetsDidChange;
@end

@class UIEvent;
/// Button with minimal tappable size 44x44.
SWIFT_CLASS("_TtC7PRUIKit13EasyTapButton")
@interface EasyTapButton : UIButton
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
SWIFT_CLASS("_TtC7PRUIKit15PRRoundedButton")
@interface PRRoundedButton : EasyTapButton
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
@end

SWIFT_CLASS("_TtC7PRUIKit14ActivityButton")
@interface ActivityButton : PRRoundedButton
@property (nonatomic, getter=isEnabled) BOOL enabled;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_RESILIENT_CLASS("_TtC7PRUIKit16AppearanceOption")
@interface AppearanceOption : _PROptionSet
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AppearanceOption * _Nonnull popover;)
+ (AppearanceOption * _Nonnull)popover SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AppearanceOption * _Nonnull transparent;)
+ (AppearanceOption * _Nonnull)transparent SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AppearanceOption * _Nonnull invertedColor;)
+ (AppearanceOption * _Nonnull)invertedColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AppearanceOption * _Nonnull branded;)
+ (AppearanceOption * _Nonnull)branded SWIFT_WARN_UNUSED_RESULT;
- (BOOL)contains:(AppearanceOption * _Nonnull)member SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithRawValue:(NSInteger)rawValue OBJC_DESIGNATED_INITIALIZER;
@end

/// The purpose of this class is applying brand appearance to all its instances.
SWIFT_CLASS("_TtC7PRUIKit11BrandButton")
@interface BrandButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC7PRUIKit34BrandGradientPopoverBackgroundView")
@interface BrandGradientPopoverBackgroundView : PRPopoverBackgroundView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame borderColor:(UIColor * _Nullable)borderColor arrowColor:(UIColor * _Nullable)arrowColor SWIFT_UNAVAILABLE;
@end

@class NSNumber;
SWIFT_CLASS("_TtC7PRUIKit17BrandGradientView")
@interface BrandGradientView : PRGradientLayerView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame colors:(NSArray<UIColor *> * _Nonnull)colors locations:(NSArray<NSNumber *> * _Nullable)locations gradientDirection:(PRGradientDirection)direction SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame topColor:(UIColor * _Nonnull)topColor bottomColor:(UIColor * _Nonnull)bottomColor SWIFT_UNAVAILABLE;
@end

@class NSString;
SWIFT_CLASS("_TtC7PRUIKit14CustomViewCell")
@interface CustomViewCell : UITableViewCell
@property (nonatomic, strong) UIView * _Nullable view;
@property (nonatomic) UIEdgeInsets viewEdgeInsets;
/// top and bottom insets are ignored
@property (nonatomic) UIEdgeInsets custormSeparatorInset;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7PRUIKit10ButtonCell")
@interface ButtonCell : CustomViewCell
@property (nonatomic, readonly, strong) UIButton * _Nullable button;
@property (nonatomic) CGFloat height;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@interface CALayer (SWIFT_EXTENSION(PRUIKit))
- (void)applySketchShadowWithColor:(UIColor * _Nonnull)color alpha:(float)alpha x:(CGFloat)x y:(CGFloat)y blur:(CGFloat)blur spread:(CGFloat)spread;
@end

SWIFT_CLASS("_TtC7PRUIKit14ContentMetrics")
@interface ContentMetrics : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat issueCellNibMargin;)
+ (CGFloat)issueCellNibMargin SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat compactSideInset;)
+ (CGFloat)compactSideInset SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat regularSideInset;)
+ (CGFloat)regularSideInset SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat sideInset;)
+ (CGFloat)sideInset SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat interArticleSpacing;)
+ (CGFloat)interArticleSpacing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat compactInteritemSpacing;)
+ (CGFloat)compactInteritemSpacing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat regularInteritemSpacing;)
+ (CGFloat)regularInteritemSpacing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat interitemSpacing;)
+ (CGFloat)interitemSpacing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat horizontalScrollerInteritemSpacing;)
+ (CGFloat)horizontalScrollerInteritemSpacing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat lineSpacing;)
+ (CGFloat)lineSpacing SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat gridCellHeightToWidthRatio;)
+ (CGFloat)gridCellHeightToWidthRatio SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGSize gridCellSize;)
+ (CGSize)gridCellSize SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGSize mediumGridCellSize;)
+ (CGSize)mediumGridCellSize SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGSize maxGridCellSize;)
+ (CGSize)maxGridCellSize SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat popoverContentSideInset;)
+ (CGFloat)popoverContentSideInset SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat featuredCatalogSectionMultiplier;)
+ (CGFloat)featuredCatalogSectionMultiplier SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat catalogThumbnailRatio;)
+ (CGFloat)catalogThumbnailRatio SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat actionButtonHeight;)
+ (CGFloat)actionButtonHeight SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat separatorWidth;)
+ (CGFloat)separatorWidth SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat thumbnailCornerRadius;)
+ (CGFloat)thumbnailCornerRadius SWIFT_WARN_UNUSED_RESULT;
+ (CGSize)gridCellSizeWith:(CGFloat)multiplier SWIFT_WARN_UNUSED_RESULT;
+ (CGFloat)coBrandingBannerHeightWithHorizontalSize:(UIUserInterfaceSizeClass)horizontalSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL_NAMED("DiscardableViewController")
@protocol PRDiscardableViewController
@property (nonatomic, readonly) BOOL isDiscardableFromTopOfNavigation;
@end

@class UITraitCollection;
@class UIImage;
SWIFT_CLASS("_TtC7PRUIKit16DynamicImageView")
@interface DynamicImageView : UIImageView
@property (nonatomic, copy) UIImage * _Nonnull (^ _Nonnull dynamicImageProvider)(UITraitCollection * _Nonnull);
- (nonnull instancetype)initWithDynamicImageProvider:(UIImage * _Nonnull (^ _Nonnull)(UITraitCollection * _Nonnull))dynamicImageProvider OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC7PRUIKit33FlippableCollectionViewFlowLayout")
@interface FlippableCollectionViewFlowLayout : UICollectionViewFlowLayout
@property (nonatomic, readonly) BOOL flipsHorizontallyInOppositeLayoutDirection;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UILabel;
@class PRFollowButton;
SWIFT_CLASS("_TtC7PRUIKit16FollowHeaderView")
@interface FollowHeaderView : UIView
@property (nonatomic, readonly, weak) IBOutlet UILabel * _Nullable label;
@property (nonatomic, readonly, weak) IBOutlet UIImageView * _Nullable imageView;
@property (nonatomic, readonly, weak) IBOutlet PRFollowButton * _Nullable button;
@property (nonatomic) CGFloat sideInset;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)setImage:(UIImage * _Nullable)image animated:(BOOL)animated;
- (void)setTitle:(NSString * _Nullable)title;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

/// Superclass for Views that comply with MVC pattern
SWIFT_CLASS("_TtC7PRUIKit9SwiftView")
@interface SwiftView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC7PRUIKit14GetStartedView")
@interface GetStartedView : SwiftView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UIViewController;
SWIFT_PROTOCOL("_TtP7PRUIKit23GlobalSearchSupportable_")
@protocol GlobalSearchSupportable
- (void)showGlobalSearchWithText:(NSString * _Nullable)text completionHandler:(void (^ _Nonnull)(UIViewController * _Nullable))completionHandler;
@end

SWIFT_CLASS("_TtC7PRUIKit9Separator")
@interface Separator : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC7PRUIKit10HSeparator")
@interface HSeparator : Separator
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
@end

SWIFT_PROTOCOL("_TtP7PRUIKit17HighlightableText_")
@protocol HighlightableText
- (void)highlightPhrases:(NSArray<NSString *> * _Nonnull)phrases;
@end

/// This class is used as a workaround for one weird bug - if you try to use UIActivityIndicatorView inside of any UICollectionViewCell,
/// the animation will be stopped by iOS.
SWIFT_CLASS("_TtC7PRUIKit20InfiniteActivityView")
@interface InfiniteActivityView : UIActivityIndicatorView
- (void)stopAnimating;
- (nonnull instancetype)initWithActivityIndicatorStyle:(UIActivityIndicatorViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7PRUIKit22InsetableNavigationBar")
@interface InsetableNavigationBar : UINavigationBar
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (void)didAddSubview:(UIView * _Nonnull)subview;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7PRUIKit9IntroView")
@interface IntroView : SwiftView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7PRUIKit19IssuesRemainingView")
@interface IssuesRemainingView : UIView
@property (nonatomic) NSInteger count;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

@class UINavigationController;
@class UINavigationItem;
/// Use this class when you have layout similar to standard large navigation bar and you want to hide and present navigation bar title in
/// the same way as for standard large navigation bar.
SWIFT_CLASS("_TtC7PRUIKit33LargeNavigationBarSimulationActor")
@interface LargeNavigationBarSimulationActor : NSObject
@property (nonatomic) CGFloat difference;
@property (nonatomic, readonly, weak) UIView * _Nullable largeTitleView;
- (nonnull instancetype)initWithNavigationController:(UINavigationController * _Nonnull)navigationController largeTitleView:(UIView * _Nonnull)largeTitleView navigationItem:(UINavigationItem * _Nonnull)navigationItem titleView:(UIView * _Nullable)titleView;
- (nonnull instancetype)initWithNavigationController:(UINavigationController * _Nonnull)navigationController largeTitleView:(UIView * _Nonnull)largeTitleView navigationItem:(UINavigationItem * _Nonnull)navigationItem titleView:(UIView * _Nullable)titleView navigationBarTintColor:(UIColor * _Nullable)navigationBarTintColor hideShadow:(BOOL)hideShadow OBJC_DESIGNATED_INITIALIZER;
- (void)onScrollViewDidScroll;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Along with <code>UINavigationItem+LargeTitleView</code> allows to present
/// custom title view in the way the navigation bar’s large title’s presented.
SWIFT_CLASS("_TtC7PRUIKit27LargeTitleViewNavigationBar")
@interface LargeTitleViewNavigationBar : InsetableNavigationBar
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSLayoutXAxisAnchor;
@class NSLayoutYAxisAnchor;
@class NSLayoutDimension;
SWIFT_PROTOCOL("_TtP7PRUIKit14LayoutGuidable_")
@protocol LayoutGuidable
@property (nonatomic, readonly, strong) NSLayoutXAxisAnchor * _Nonnull leadingAnchor;
@property (nonatomic, readonly, strong) NSLayoutXAxisAnchor * _Nonnull trailingAnchor;
@property (nonatomic, readonly, strong) NSLayoutXAxisAnchor * _Nonnull leftAnchor;
@property (nonatomic, readonly, strong) NSLayoutXAxisAnchor * _Nonnull rightAnchor;
@property (nonatomic, readonly, strong) NSLayoutYAxisAnchor * _Nonnull topAnchor;
@property (nonatomic, readonly, strong) NSLayoutYAxisAnchor * _Nonnull bottomAnchor;
@property (nonatomic, readonly, strong) NSLayoutDimension * _Nonnull widthAnchor;
@property (nonatomic, readonly, strong) NSLayoutDimension * _Nonnull heightAnchor;
@property (nonatomic, readonly, strong) NSLayoutXAxisAnchor * _Nonnull centerXAnchor;
@property (nonatomic, readonly, strong) NSLayoutYAxisAnchor * _Nonnull centerYAnchor;
@end

@interface MBProgressHUD (SWIFT_EXTENSION(PRUIKit))
+ (nonnull instancetype)showLoading SWIFT_WARN_UNUSED_RESULT;
+ (nonnull instancetype)showLoadingWithGraceTime:(NSTimeInterval)graceTime SWIFT_WARN_UNUSED_RESULT;
+ (nonnull instancetype)showKeyWindowHudWithTitle:(NSString * _Nullable)title message:(NSString * _Nullable)message animated:(BOOL)animated SWIFT_WARN_UNUSED_RESULT;
+ (nonnull instancetype)showKeyWindowHudWithTitle:(NSString * _Nullable)title message:(NSString * _Nullable)message animated:(BOOL)animated graceTime:(NSTimeInterval)graceTime SWIFT_WARN_UNUSED_RESULT;
@end

@interface NSLayoutManager (SWIFT_EXTENSION(PRUIKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat defaultHyphenationFactor;)
+ (CGFloat)defaultHyphenationFactor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isHyphenationEnabled;)
+ (BOOL)isHyphenationEnabled SWIFT_WARN_UNUSED_RESULT;
@end

@interface NSNotification (SWIFT_EXTENSION(PRUIKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull fontSizeAdjustmentChange;)
+ (NSNotificationName _Nonnull)fontSizeAdjustmentChange SWIFT_WARN_UNUSED_RESULT;
@end

@interface NSObject (SWIFT_EXTENSION(PRUIKit))
- (void)logDealloc;
@end

@interface NSURL (SWIFT_EXTENSION(PRUIKit))
- (void)openWithPerformDeepLinkCheck:(BOOL)performDeepLinkCheck;
- (void)open;
@end

SWIFT_PROTOCOL("_TtP7PRUIKit24NavigationBarDismissable_")
@protocol NavigationBarDismissable
- (void)showBarsAnimated:(BOOL)animated;
- (void)dismissBarsAnimated:(BOOL)animated delayed:(BOOL)delayed;
@end

/// Container that resolves user interaction issues caused by auto layout.
SWIFT_CLASS_NAMED("NavigationItemTitleViewContainer")
@interface PRNavigationItemTitleViewContainer : UIView
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@interface PRActivityVC (SWIFT_EXTENSION(PRUIKit))
- (void)setupAccessibility;
@end

@interface PRAppStyle (SWIFT_EXTENSION(PRUIKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIImage * _Nullable roundShadeImage;)
+ (UIImage * _Nullable)roundShadeImage SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIImage * _Nullable roundSelectionImage;)
+ (UIImage * _Nullable)roundSelectionImage SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIImage * _Nullable roundLightSelectionImage;)
+ (UIImage * _Nullable)roundLightSelectionImage SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, PRBarButtonSystemItem, open) {
  PRBarButtonSystemItemDone = 0,
  PRBarButtonSystemItemCancel = 1,
  PRBarButtonSystemItemEdit = 2,
  PRBarButtonSystemItemSave = 3,
  PRBarButtonSystemItemAdd = 4,
  PRBarButtonSystemItemFlexibleSpacee = 5,
  PRBarButtonSystemItemFixedSpace = 6,
  PRBarButtonSystemItemBack = 7,
  PRBarButtonSystemItemActionMenu = 8,
  PRBarButtonSystemItemAppMenu = 9,
  PRBarButtonSystemItemClose = 10,
  PRBarButtonSystemItemSearch = 11,
  PRBarButtonSystemItemUndefined = 12,
  PRBarButtonSystemItemNew = 13,
};

@interface PRFollowButton (SWIFT_EXTENSION(PRUIKit))
- (void)setupAccessibility;
@end

SWIFT_CLASS("_TtC7PRUIKit16PRImageExtension")
@interface PRImageExtension : NSObject
@property (nonatomic, readonly, strong) UIImage * _Nullable chevronLeft;
@property (nonatomic, readonly, strong) UIImage * _Nullable chevronRight;
@property (nonatomic, readonly, strong) UIImage * _Nullable close;
@property (nonatomic, readonly, strong) UIImage * _Nullable menu;
@property (nonatomic, readonly, strong) UIImage * _Nullable back;
@property (nonatomic, readonly, strong) UIImage * _Nullable more;
@property (nonatomic, readonly, strong) UIImage * _Nullable search;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PRMenu;
@class PRMenuItem;
SWIFT_PROTOCOL_NAMED("PRMenuBottomBar")
@protocol PRMenuBottomBar <NSObject>
@property (nonatomic, readonly) BOOL isBarHidden;
@property (nonatomic, readonly, strong) UIViewController * _Nonnull menuContainerVC;
@property (nonatomic, strong) PRMenu * _Nullable menu;
- (UIView * _Nullable)viewFor:(PRMenuItem * _Nonnull)item SWIFT_WARN_UNUSED_RESULT;
- (void)insertAttachedSubview:(UIView * _Nonnull)subview hideShadow:(BOOL)hideShadow;
- (void)showAnimated:(BOOL)animated;
- (void)hideAnimated:(BOOL)animated;
@end

@class NSURLComponents;
@interface PRSafariVC (SWIFT_EXTENSION(PRUIKit))
- (BOOL)handleInitialPresentation:(NSURL * _Nonnull)url components:(NSURLComponents * _Nonnull)components SWIFT_WARN_UNUSED_RESULT;
- (WKNavigationActionPolicy)handleURLChanges:(NSURL * _Nonnull)url components:(NSURLComponents * _Nonnull)components SWIFT_WARN_UNUSED_RESULT;
- (void)resetLastSizeParameter;
@end

@class CAShapeLayer;
SWIFT_CLASS("_TtC7PRUIKit16PRShapeLayerView")
@interface PRShapeLayerView : UIView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) CAShapeLayer * _Nonnull layer;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@interface PRSwitchButton (SWIFT_EXTENSION(PRUIKit))
- (void)setupAccessibility;
- (void)updateAccessibility;
@end

/// UITextField with PR-style applied
SWIFT_CLASS("_TtC7PRUIKit11PRTextField")
@interface PRTextField : UITextField
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
@end

@interface PRTextField (SWIFT_EXTENSION(PRUIKit))
- (void)updateAppearance;
@end

@class UIGestureRecognizer;
@interface PRUINavigationController (SWIFT_EXTENSION(PRUIKit)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC7PRUIKit15PRViewExtension")
@interface PRViewExtension : NSObject
@property (nonatomic, strong) AppearanceOption * _Nonnull appearanceOptions;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface PRViewExtension (SWIFT_EXTENSION(PRUIKit))
- (void)removeAllSubviews;
@end

@interface PRViewExtension (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@end

@interface PRViewExtension (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, strong) UIViewController * _Nullable contentController;
@end

@interface PRViewExtension (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly, strong) UIView * _Nonnull topHairline;
@property (nonatomic, readonly, strong) UIView * _Nonnull bottomHairline;
@end

SWIFT_CLASS("_TtC7PRUIKit18ReaderBookmarkView")
@interface ReaderBookmarkView : UIControl
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC7PRUIKit18ReaderProgressView")
@interface ReaderProgressView : UIControl
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_PROTOCOL("_TtP7PRUIKit10Reportable_")
@protocol Reportable
- (void)report;
@end

SWIFT_CLASS("_TtC7PRUIKit10RibbonView")
@interface RibbonView : UIView
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, strong) UIColor * _Nullable textColor;
@property (nonatomic) CGFloat fontSize;
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
@property (nonatomic) CGFloat ribbonHeight;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7PRUIKit24SelectionActionsMenuCell")
@interface SelectionActionsMenuCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC7PRUIKit10SignInView")
@interface SignInView : BrandGradientView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7PRUIKit27SimpleTitleHeaderFooterView")
@interface SimpleTitleHeaderFooterView : UITableViewHeaderFooterView
- (nonnull instancetype)initWithReuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC7PRUIKit16SubtitleTextCell")
@interface SubtitleTextCell : CustomViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7PRUIKit10SwitchView")
@interface SwitchView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC7PRUIKit21TabCollectionViewCell")
@interface TabCollectionViewCell : UICollectionViewCell
@property (nonatomic, getter=isSelected) BOOL selected;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;
@class NSIndexPath;
@class UICollectionViewLayout;
SWIFT_CLASS("_TtC7PRUIKit9TabsPanel")
@interface TabsPanel : UIView <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UIFont;
SWIFT_CLASS("_TtC7PRUIKit9TagButton")
@interface TagButton : UIButton
- (nonnull instancetype)init;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)configureWithTitle:(NSString * _Nonnull)title font:(UIFont * _Nonnull)font;
@end

SWIFT_CLASS("_TtC7PRUIKit8TextCell")
@interface TextCell : CustomViewCell
@property (nonatomic, readonly, strong) UILabel * _Nullable label;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextView;
SWIFT_CLASS("_TtC7PRUIKit12TextViewCell")
@interface TextViewCell : CustomViewCell
@property (nonatomic, readonly, strong) UITextView * _Nullable textView;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7PRUIKit24TextViewHeaderFooterView")
@interface TextViewHeaderFooterView : UITableViewHeaderFooterView
@property (nonatomic, readonly, strong) UITextView * _Nonnull textView;
- (nonnull instancetype)initWithReuseIdentifier:(NSString * _Nullable)reuseIdentifier SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)updateAppearance;
@end

SWIFT_CLASS("_TtC7PRUIKit19ThumbnailShadowView")
@interface ThumbnailShadowView : UIView
@property (nonatomic) BOOL isShadowHidden;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
@end

/// This view intercepts only those events that are suitable for its subviews.
SWIFT_CLASS("_TtC7PRUIKit24TransparentContainerView")
@interface TransparentContainerView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIActivityIndicatorView (SWIFT_EXTENSION(PRUIKit))
+ (nonnull instancetype)styledActivityIndicatorWithStyle:(UIActivityIndicatorViewStyle)style SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIApplication (SWIFT_EXTENSION(PRUIKit))
/// With <code>performDeepLinkCheck</code> on,  makes an attempts to open a url as a deep link via <code>delegate</code>.
/// If not successfull, proceeds with regular <code>open</code>.
- (void)open:(NSURL * _Nonnull)url performDeepLinkCheck:(BOOL)performDeepLinkCheck;
@end

@class PRPromise;
@interface UIApplication (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly) BOOL isInBackground;
@property (nonatomic, readonly) BOOL isActive;
@property (nonatomic, readonly, strong) PRPromise * _Nonnull didBecomeActive;
@end

@interface UIBarButtonItem (SWIFT_EXTENSION(PRUIKit))
+ (UIBarButtonItem * _Nullable)barButtonWithSystemItem:(enum PRBarButtonSystemItem)systemItem target:(id _Nullable)target action:(SEL _Nullable)action SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIBarButtonItem (SWIFT_EXTENSION(PRUIKit))
+ (UIBarButtonItem * _Nullable)brandTitleItemWithSystemItem:(enum PRBarButtonSystemItem)systemItem font:(UIFont * _Nullable)font target:(id _Nullable)target action:(SEL _Nullable)action SWIFT_WARN_UNUSED_RESULT;
+ (UIBarButtonItem * _Nullable)brandTitleItemWithSystemItem:(enum PRBarButtonSystemItem)systemItem font:(UIFont * _Nullable)font action:(void (^ _Nonnull)(void))action SWIFT_WARN_UNUSED_RESULT;
/// This method is deprecated and should be replaced with <code>brandTitleItem(systemItem:font:target:action:)</code>
+ (UIBarButtonItem * _Nonnull)brandTitleItemWithTitle:(NSString * _Nullable)title font:(UIFont * _Nullable)font target:(id _Nullable)target action:(SEL _Nullable)action SWIFT_WARN_UNUSED_RESULT;
/// This method is deprecated and should be replaced with <code>brandTitleItem(systemItem:font:action:)</code>
+ (UIBarButtonItem * _Nonnull)brandTitleItemWithTitle:(NSString * _Nullable)title font:(UIFont * _Nullable)font action:(void (^ _Nonnull)(void))action SWIFT_WARN_UNUSED_RESULT;
+ (UIBarButtonItem * _Nullable)brandButtonItemWithSystemItem:(enum PRBarButtonSystemItem)systemItem target:(id _Nullable)target action:(SEL _Nullable)action SWIFT_WARN_UNUSED_RESULT;
+ (UIBarButtonItem * _Nullable)brandButtonItemWithSystemItem:(enum PRBarButtonSystemItem)systemItem action:(void (^ _Nonnull)(void))action SWIFT_WARN_UNUSED_RESULT;
/// This method is deprecated and should be replaced with <code>brandButtonItem(systemItem:target:action:)</code>
+ (UIBarButtonItem * _Nonnull)brandButtonItemWithTitle:(NSString * _Nullable)title target:(id _Nullable)target action:(SEL _Nullable)action SWIFT_WARN_UNUSED_RESULT;
/// This method is deprecated and should be replaced with <code>brandButtonItem(systemItem:action:)</code>
+ (UIBarButtonItem * _Nonnull)brandButtonItemWithTitle:(NSString * _Nullable)title action:(void (^ _Nonnull)(void))action SWIFT_WARN_UNUSED_RESULT;
@end

@class AccessibilityId;
SWIFT_UNAVAILABLE
@interface UIBarItem (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, strong) AccessibilityId * _Nullable accessibilityId;
@end

@interface UIButton (SWIFT_EXTENSION(PRUIKit))
- (BOOL)isEasyTapPointInside:(CGPoint)point with:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
@end

@class UIButtonConfiguration;
SWIFT_UNAVAILABLE
@interface UIButton (SWIFT_EXTENSION(PRUIKit))
+ (UIButtonConfiguration * _Nonnull)prDefaultConfiguration SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIButton (SWIFT_EXTENSION(PRUIKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIButton * _Nonnull simple;)
+ (UIButton * _Nonnull)simple SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIButton * _Nonnull action;)
+ (UIButton * _Nonnull)action SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIButton * _Nonnull clearAction;)
+ (UIButton * _Nonnull)clearAction SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIButton * _Nonnull white;)
+ (UIButton * _Nonnull)white SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIColor (SWIFT_EXTENSION(PRUIKit))
- (nonnull instancetype)initWithStartColor:(UIColor * _Nonnull)startColor endColor:(UIColor * _Nonnull)endColor location:(CGFloat)location;
@end

@interface UIColor (SWIFT_EXTENSION(PRUIKit))
- (NSString * _Nullable)rgbaString SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIColor (SWIFT_EXTENSION(PRUIKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull selectionColor;)
+ (UIColor * _Nonnull)selectionColor SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIColor (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly, strong) UIColor * _Nonnull invertedColor;
@end

@interface UIColor (SWIFT_EXTENSION(PRUIKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull subtitle1;)
+ (UIColor * _Nonnull)subtitle1 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull subtitle2;)
+ (UIColor * _Nonnull)subtitle2 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull subtitle3;)
+ (UIColor * _Nonnull)subtitle3 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull detailsText;)
+ (UIColor * _Nonnull)detailsText SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull articleTitle;)
+ (UIColor * _Nonnull)articleTitle SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull articleText;)
+ (UIColor * _Nonnull)articleText SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIColor (SWIFT_EXTENSION(PRUIKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull translationBackgroundColor;)
+ (UIColor * _Nonnull)translationBackgroundColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull sampleContentTintColor;)
+ (UIColor * _Nonnull)sampleContentTintColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull freeRibbonColor;)
+ (UIColor * _Nonnull)freeRibbonColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull globalBlueColor;)
+ (UIColor * _Nonnull)globalBlueColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull globalDestructiveColor;)
+ (UIColor * _Nonnull)globalDestructiveColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nullable darkLogoColor;)
+ (UIColor * _Nullable)darkLogoColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull menuBarTint;)
+ (UIColor * _Nonnull)menuBarTint SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull translucentMenuBarTint;)
+ (UIColor * _Nonnull)translucentMenuBarTint SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull tableViewSectionHeaderFooterBackground;)
+ (UIColor * _Nonnull)tableViewSectionHeaderFooterBackground SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull bylineTextColor;)
+ (UIColor * _Nonnull)bylineTextColor SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIColor (SWIFT_EXTENSION(PRUIKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<UIColor *> * _Nonnull brandGradientColors;)
+ (NSArray<UIColor *> * _Nonnull)brandGradientColors SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull feedBackground;)
+ (UIColor * _Nonnull)feedBackground SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull coverPlaceholderTint;)
+ (UIColor * _Nonnull)coverPlaceholderTint SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull activityIndicator;)
+ (UIColor * _Nonnull)activityIndicator SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull articleDetailsViewBackground;)
+ (UIColor * _Nonnull)articleDetailsViewBackground SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull tabBarBackground;)
+ (UIColor * _Nonnull)tabBarBackground SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull thumbnailBackground;)
+ (UIColor * _Nonnull)thumbnailBackground SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull barTintColor;)
+ (UIColor * _Nonnull)barTintColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nullable customBarTint;)
+ (UIColor * _Nullable)customBarTint SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull searchBarBackground;)
+ (UIColor * _Nonnull)searchBarBackground SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIFont (SWIFT_EXTENSION(PRUIKit))
+ (UIFont * _Nullable)customFontWithName:(NSString * _Nonnull)name sizeOfTextStyle:(UIFontTextStyle _Nonnull)style pointSizeCorrection:(CGFloat)pointSizeCorrection SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIFont (SWIFT_EXTENSION(PRUIKit))
+ (UIFont * _Nonnull)preferredFontForTextStyle:(UIFontTextStyle _Nonnull)style pointSizeCorrection:(CGFloat)pointSizeCorrection SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nonnull)preferredFontForTextStyle:(UIFontTextStyle _Nonnull)style scale:(CGFloat)scale SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIFont (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly) UIFontWeight weight;
@end

@interface UIFont (SWIFT_EXTENSION(PRUIKit))
+ (UIFont * _Nonnull)systemFontWithSizeOfTextStyle:(UIFontTextStyle _Nonnull)style pointSizeCorrection:(CGFloat)pointSizeCorrection SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use `prefererredFontForTextStyle:pointSizeCorrection:` instead or specify weight explicitly");
+ (UIFont * _Nonnull)systemFontWithSizeOfTextStyle:(UIFontTextStyle _Nonnull)style weight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nonnull)systemFontWithSizeOfTextStyle:(UIFontTextStyle _Nonnull)style pointSizeCorrection:(CGFloat)pointSizeCorrection weight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nonnull)systemFontWithSizeOfTextStyle:(UIFontTextStyle _Nonnull)style scale:(CGFloat)scale weight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIFont (SWIFT_EXTENSION(PRUIKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UITraitCollection * _Nonnull standardContentCategoryTraitCollection;)
+ (UITraitCollection * _Nonnull)standardContentCategoryTraitCollection SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nonnull)scalableSystemFontWithSizeOfTextStyle:(UIFontTextStyle _Nonnull)style pointSizeCorrection:(CGFloat)pointSizeCorrection weight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nonnull)scalablePreferredFontForTextStyle:(UIFontTextStyle _Nonnull)style pointSizeCorrection:(CGFloat)pointSizeCorrection SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nullable)scalableCustomFontWithName:(NSString * _Nonnull)name sizeOfTextStyle:(UIFontTextStyle _Nonnull)style pointSizeCorrection:(CGFloat)pointSizeCorrection SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL isScalable;
@end

@interface UIFont (SWIFT_EXTENSION(PRUIKit))
- (UIFont * _Nonnull)scaledFontWithContentSizeCategoryAdjustment:(NSInteger)adjustment clamping:(UIContentSizeCategory _Nonnull)from to:(UIContentSizeCategory _Nonnull)to SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)scaledFontWithContentSizeCategoryAdjustment:(NSInteger)adjustment SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)scaledFontWithContentSizeCategoryAdjustment SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)scaledFontWithContentSizeCategoryAdjustmentClampingFrom:(UIContentSizeCategory _Nonnull)from to:(UIContentSizeCategory _Nonnull)to SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)scaledPointSizeWithContentSizeCategoryAdjustment:(NSInteger)adjustment clamping:(UIContentSizeCategory _Nonnull)from to:(UIContentSizeCategory _Nonnull)to SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)scaledPointSizeWithContentSizeCategoryAdjustment:(NSInteger)adjustment SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)scaledPointSizeWithContentSizeCategoryAdjustmentClampingFrom:(UIContentSizeCategory _Nonnull)from to:(UIContentSizeCategory _Nonnull)to SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)scaledPointSizeWithContentSizeCategoryAdjustment SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)defaultScaledPointSize SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)defaultScaledFont SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIFont (SWIFT_EXTENSION(PRUIKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull caption;)
+ (UIFont * _Nonnull)caption SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull subheadline;)
+ (UIFont * _Nonnull)subheadline SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull body;)
+ (UIFont * _Nonnull)body SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull headlineBold;)
+ (UIFont * _Nonnull)headlineBold SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull footnoteBold;)
+ (UIFont * _Nonnull)footnoteBold SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull buttonTitle;)
+ (UIFont * _Nonnull)buttonTitle SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIFont (SWIFT_EXTENSION(PRUIKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nullable articleBody;)
+ (UIFont * _Nullable)articleBody SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nullable articleAnnotation;)
+ (UIFont * _Nullable)articleAnnotation SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nonnull articleTitle;)
+ (UIFont * _Nonnull)articleTitle SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nonnull)articleTitleWithTextStyle:(UIFontTextStyle _Nonnull)textStyle pointSizeCorrection:(CGFloat)pointSizeCorrection weight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nullable articleSubtitle;)
+ (UIFont * _Nullable)articleSubtitle SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nullable articleCaption;)
+ (UIFont * _Nullable)articleCaption SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nullable articleByline;)
+ (UIFont * _Nullable)articleByline SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nullable)articleBodyWithPointSizeCorrection:(CGFloat)pointSizeCorrection SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIFont * _Nullable articlePreviewBody;)
+ (UIFont * _Nullable)articlePreviewBody SWIFT_WARN_UNUSED_RESULT;
+ (UIFont * _Nonnull)feedSectionWithWeight:(UIFontWeight)weight SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIFontDescriptor (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly) UIFontWeight weight;
@end

@interface UIFontMetrics (SWIFT_EXTENSION(PRUIKit))
- (UIFont * _Nonnull)scaledFontForFont:(UIFont * _Nonnull)font contentCategoryAdjustment:(NSInteger)contentCategoryAdjustment SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)scaledFontForFont:(UIFont * _Nonnull)font contentCategoryAdjustment:(NSInteger)contentCategoryAdjustment clampingFrom:(UIContentSizeCategory _Nonnull)from to:(UIContentSizeCategory _Nonnull)to SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)scaledValueForValue:(CGFloat)value contentCategoryAdjustment:(NSInteger)contentCategoryAdjustment SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)scaledValueForValue:(CGFloat)value contentCategoryAdjustment:(NSInteger)contentCategoryAdjustment clampingFrom:(UIContentSizeCategory _Nonnull)from to:(UIContentSizeCategory _Nonnull)to SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIImage (SWIFT_EXTENSION(PRUIKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PRImageExtension * _Nonnull pr;)
+ (PRImageExtension * _Nonnull)pr SWIFT_WARN_UNUSED_RESULT;
@end

@interface UILabel (SWIFT_EXTENSION(PRUIKit)) <HighlightableText>
- (void)highlightPhrases:(NSArray<NSString *> * _Nonnull)phrases;
@end

@interface UILabel (SWIFT_EXTENSION(PRUIKit))
- (void)updateAppearance;
- (void)updateAppearanceOfLinks;
@end

@interface UILabel (SWIFT_EXTENSION(PRUIKit))
- (nonnull instancetype)initWithFont:(UIFont * _Nonnull)font color:(UIColor * _Nullable)color numberOfLines:(NSInteger)numberOfLines;
- (nonnull instancetype)initWithText:(NSString * _Nonnull)text;
@end

@class NSAttributedString;
SWIFT_CLASS("_TtC7PRUIKit14UILabelHidable")
@interface UILabelHidable : UILabel
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, strong) NSAttributedString * _Nullable attributedText;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@interface UILayoutGuide (SWIFT_EXTENSION(PRUIKit)) <LayoutGuidable>
@end

@interface UINavigationBar (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic) CGFloat largeTitleOffset;
@end

enum BackgroundType : NSInteger;
@interface UINavigationBar (SWIFT_EXTENSION(PRUIKit))
- (void)setupScrollEdgeAppearanceWithBackgroundType:(enum BackgroundType)backgroundType color:(UIColor * _Nullable)color;
- (void)setupStandardAppearanceWithBackgroundType:(enum BackgroundType)backgroundType color:(UIColor * _Nullable)color;
- (void)setupAppearanceWithBackgroundType:(enum BackgroundType)backgroundType color:(UIColor * _Nullable)color;
- (void)setupAppearanceWithTitleTextAttributes:(NSDictionary<NSAttributedStringKey, id> * _Nonnull)attributes;
- (void)setupTitleTextAttributes:(NSDictionary<NSAttributedStringKey, id> * _Nonnull)attributes;
@end

@interface UINavigationBarAppearance (SWIFT_EXTENSION(PRUIKit))
@end

typedef SWIFT_ENUM(NSInteger, BackgroundType, open) {
  BackgroundTypeDefault = 0,
  BackgroundTypeOpaque = 1,
  BackgroundTypeTransparent = 2,
};

@interface UINavigationController (SWIFT_EXTENSION(PRUIKit))
- (void)pushViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated completion:(void (^ _Nullable)(void))completion;
- (void)popViewControllerWithAnimated:(BOOL)animated completion:(void (^ _Nullable)(void))completion;
- (void)popToViewController:(UIViewController * _Nonnull)viewController animated:(BOOL)animated completion:(void (^ _Nullable)(void))completion;
@end

@interface UINavigationItem (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, strong) UIView * _Nullable largeTitleView;
@property (nonatomic, strong) UIView * _Nullable standardTitleView;
@end

@interface UINavigationItem (SWIFT_EXTENSION(PRUIKit))
- (void)setLeftBarButtonItems:(NSArray<UIBarButtonItem *> * _Nullable)items animated:(BOOL)animated inset:(CGFloat)inset;
- (void)setRightBarButtonItems:(NSArray<UIBarButtonItem *> * _Nullable)items animated:(BOOL)animated inset:(CGFloat)inset;
@end

@interface UINavigationItem (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly, strong) UIBarButtonItem * _Nullable firstFromEdgeLeftBarButtonItem;
@property (nonatomic, readonly, strong) UIBarButtonItem * _Nullable firstFromEdgeRightBarButtonItem;
- (NSArray<UIBarButtonItem *> * _Nonnull)allBarButtons SWIFT_WARN_UNUSED_RESULT;
- (void)applyBarButtonsTintColor:(UIColor * _Nonnull)color;
- (void)applyBarButtonsAlpha:(CGFloat)alpha;
@end

@interface UIStackView (SWIFT_EXTENSION(PRUIKit))
- (void)setTextColor:(UIColor * _Nonnull)color;
@end

@interface UIStackView (SWIFT_EXTENSION(PRUIKit))
- (void)forceRemoveArrangedSubview:(UIView * _Nonnull)view;
- (void)removeArrangedSubviews;
- (void)addArrangedFlexibleSpace;
- (void)insertArrangedFlexibleSpaceAfter:(UIView * _Nonnull)view;
- (void)addArrangedFixedSpaceWithSpace:(CGFloat)space;
- (void)insertArrangedFixedSpaceWithSpace:(CGFloat)space after:(UIView * _Nonnull)view;
- (void)trimStretchableSubviewSpaces;
@end

@interface UITableView (SWIFT_EXTENSION(PRUIKit))
- (void)hideExtraRows;
@end

@interface UITextField (SWIFT_EXTENSION(PRUIKit))
- (UIButton * _Nullable)getClearButton SWIFT_WARN_UNUSED_RESULT;
@end

@interface UITraitCollection (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly) BOOL isDark;
@property (nonatomic, readonly) BOOL isLight;
@property (nonatomic, readonly) BOOL isRTL;
@property (nonatomic, strong) AppearanceOption * _Nonnull appearanceOptions;
@end

@interface UIView (SWIFT_EXTENSION(PRUIKit)) <LayoutGuidable>
@end

@interface UIView (SWIFT_EXTENSION(PRUIKit))
- (void)forceRelayout;
@end

@interface UIView (SWIFT_EXTENSION(PRUIKit))
- (nonnull instancetype)initWithBackgroundColor:(UIColor * _Nullable)backgroundColor;
@end

SWIFT_UNAVAILABLE
@interface UIView (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, strong) AccessibilityId * _Nullable accessibilityId;
@end

@interface UIView (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly, copy) NSString * _Nonnull dimensionParams;
@end

@class NSLayoutConstraint;
@interface UIView (SWIFT_EXTENSION(PRUIKit))
- (NSArray<NSLayoutConstraint *> * _Nonnull)sizeConstraintsWithSize:(CGSize)size priority:(UILayoutPriority)priority SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSLayoutConstraint *> * _Nonnull)sizeConstraintsWithSize:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIView (SWIFT_EXTENSION(PRUIKit))
- (void)rightToLeftAllSubviews;
- (void)setRecursiveSemanticContentAttribute:(UISemanticContentAttribute)contentAttribute;
@end

@interface UIView (SWIFT_EXTENSION(PRUIKit))
- (UIView * _Nullable)superviewWithClass:(SWIFT_METATYPE(UIView) _Nonnull)type SWIFT_WARN_UNUSED_RESULT;
@end

@interface UIView (SWIFT_EXTENSION(PRUIKit))
- (NSArray<NSLayoutConstraint *> * _Nonnull)includeInto:(UIView * _Nonnull)container insets:(UIEdgeInsets)insets useSafeArea:(BOOL)useSafeArea;
- (NSArray<NSLayoutConstraint *> * _Nonnull)includeInto:(UIView * _Nonnull)container insets:(UIEdgeInsets)insets;
- (NSArray<NSLayoutConstraint *> * _Nonnull)includeInto:(UIView * _Nonnull)container;
@end

@interface UIView (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly, strong) PRViewExtension * _Nonnull pr;
@end

@class ViewTraits;
@interface UIView (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly, strong) ViewTraits * _Nonnull traits;
@end

@interface UIView (SWIFT_EXTENSION(PRUIKit))
- (void)resistHCompression;
- (void)resistVCompression;
- (void)resistHHugging;
- (void)resistVHugging;
- (void)resistCompression;
- (void)resistHugging;
@end

@interface UIView (SWIFT_EXTENSION(PRUIKit))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) CGFloat scaleCoefficient;)
+ (CGFloat)scaleCoefficient SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) CGFloat scaleCoefficient;
@property (nonatomic, readonly) CGFloat upscaleCoefficient;
@end

@interface UIView (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly, copy) NSArray<NSLayoutConstraint *> * _Nonnull inclusionConstraints;
- (void)includeIntoCenterOfContainer:(UIView * _Nonnull)container;
- (NSArray<NSLayoutConstraint *> * _Nonnull)attachTo:(id <LayoutGuidable> _Nonnull)anchor insets:(UIEdgeInsets)insets;
- (void)updateInclusionConstraints:(UIEdgeInsets)insets;
@end

@class UIVisualEffectView;
@class UIBlurEffect;
@interface UIView (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly) BOOL hasBlurEffect;
@property (nonatomic, readonly, strong) UIView * _Nullable blurContentView;
- (UIVisualEffectView * _Nonnull)addBlurSubviewWithBlurFrame:(CGRect)blurFrame style:(enum UIBlurEffectStyle)style;
- (UIVisualEffectView * _Nonnull)addBlurSubviewWithBlurFrame:(CGRect)blurFrame style:(enum UIBlurEffectStyle)style intensity:(CGFloat)intensity;
- (void)addBlurEffectWithStyle:(enum UIBlurEffectStyle)style intensity:(CGFloat)intensity;
- (void)addBlurEffectWithStyle:(enum UIBlurEffectStyle)style;
- (void)addBlurEffect:(UIBlurEffect * _Nonnull)effect color:(UIColor * _Nullable)color;
- (void)reloadBlurEffect;
- (void)addBlurEffect;
- (void)removeBlurEffect;
- (UIImage * _Nullable)blurImage:(CGFloat)blurRadius SWIFT_WARN_UNUSED_RESULT;
- (UIVisualEffectView * _Nonnull)addBlurSubviewWithBlurFrame:(CGRect)blurFrame style:(enum UIBlurEffectStyle)style color:(UIColor * _Nullable)color createBlur:(SWIFT_NOESCAPE UIVisualEffectView * _Nonnull (^ _Nonnull)(void))createBlur;
@end

@interface UIViewController (SWIFT_EXTENSION(PRUIKit))
- (void)setNavigationBarAppearance;
@end

@interface UIViewController (SWIFT_EXTENSION(PRUIKit))
- (void)showWithRegardToPresentationStyle:(UIViewController * _Nonnull)vc popoverSourceItem:(id _Nullable)popoverSourceItem popoverLayoutMargins:(UIEdgeInsets)popoverLayoutMargins animated:(BOOL)animated;
@end

@interface UIViewController (SWIFT_EXTENSION(PRUIKit)) <NavigationBarDismissable>
- (void)showBarsAnimated:(BOOL)animated;
- (void)dismissBarsAnimated:(BOOL)animated delayed:(BOOL)delayed;
@end

@interface UIViewController (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly) BOOL isBranded;
@property (nonatomic, readonly) BOOL isRootInNavigationStack;
@end

@interface UIViewController (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly) BOOL isAppContainer;
@property (nonatomic, readonly, strong) UIViewController * _Nullable presenter;
@end

@interface UIViewController (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic, readonly, strong) UIViewController * _Nonnull topMostController;
@property (nonatomic, readonly, strong) UIViewController * _Nonnull topMostFullScreenController;
- (void)dismissWithKeepTopAlert:(BOOL)keepTopAlert animated:(BOOL)animated completion:(void (^ _Nullable)(void))completion;
@end

SWIFT_CLASS("_TtC7PRUIKit17UIViewStretchable")
@interface UIViewStretchable : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

@interface NSUserDefaults (SWIFT_EXTENSION(PRUIKit))
@property (nonatomic) NSInteger fontSizeAdjustment;
@property (nonatomic) NSInteger articleDetailsFontSizeAdjustment;
@end

SWIFT_CLASS("_TtC7PRUIKit10VSeparator")
@interface VSeparator : Separator
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC7PRUIKit10ViewTraits")
@interface ViewTraits : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
