#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef PRCATALOGMODEL_SWIFT_H
#define PRCATALOGMODEL_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import PRSyntacticSugar;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PRCatalogModel",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("CatalogEntity")
@interface CatalogEntity : NSManagedObject
- (void)prepareForDeletion;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("Author")
@interface Author : CatalogEntity
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("CatalogItem")
@interface CatalogItem : NSManagedObject
- (void)prepareForDeletion;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("Book")
@interface Book : CatalogItem
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class CatalogItemContentOption;

@interface Book (SWIFT_EXTENSION(PRCatalogModel))
- (BOOL)isInMyLibraryWithContentOptions:(CatalogItemContentOption * _Nonnull)contentOptions SWIFT_WARN_UNUSED_RESULT;
@end

@class NSString;
@class NSDate;

@interface Book (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSString * _Nullable info;
@property (nonatomic, copy) NSString * _Nullable isbn;
@property (nonatomic, copy) NSDate * _Nullable publishDate;
@property (nonatomic, copy) NSString * _Nullable subtitle;
@property (nonatomic, copy) NSString * _Nullable prn;
@end


SWIFT_CLASS_NAMED("CatalogItemContent")
@interface CatalogItemContent : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("BookContent")
@interface BookContent : CatalogItemContent
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class BookFragment;

@interface BookContent (SWIFT_EXTENSION(PRCatalogModel))
- (void)addFragmentsObject:(BookFragment * _Nonnull)value;
- (void)removeFragmentsObject:(BookFragment * _Nonnull)value;
- (void)addFragments:(NSSet<BookFragment *> * _Nonnull)values;
- (void)removeFragments:(NSSet<BookFragment *> * _Nonnull)values;
@end

@class ContentLocator;

@interface BookContent (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) ContentLocator * _Nullable currentLocator;
@property (nonatomic, copy) NSSet<BookFragment *> * _Nullable fragments;
@end


SWIFT_CLASS_NAMED("BookFragment")
@interface BookFragment : NSManagedObject
- (void)awakeFromInsert;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class FragmentStartLocator;
@class FragmentEndLocator;

@interface BookFragment (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) FragmentStartLocator * _Nonnull startLocator;
@property (nonatomic, strong) FragmentEndLocator * _Nonnull endLocator;
@property (nonatomic, copy) NSString * _Nullable resourceTitle;
@property (nonatomic, copy) NSString * _Nullable pageLabel;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSDate * _Nonnull created;
@property (nonatomic, strong) BookContent * _Nonnull content;
@end


SWIFT_CLASS_NAMED("BookLicense")
@interface BookLicense : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface BookLicense (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull bookId;
@property (nonatomic, copy) NSDate * _Nullable endDate;
@property (nonatomic, copy) NSDate * _Nonnull startDate;
@end


SWIFT_CLASS_NAMED("Bookmark")
@interface Bookmark : BookFragment
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("Catalog")
@interface Catalog : NSManagedObject
- (void)awakeFromInsert;
- (void)prepareForDeletion;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("Books")
@interface Books : Catalog
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class PressCatalog;

@interface Books (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) PressCatalog * _Nonnull pressCatalog;
@end





@interface Catalog (SWIFT_EXTENSION(PRCatalogModel))
- (void)addItemsObject:(CatalogItem * _Nonnull)value;
- (void)removeItemsObject:(CatalogItem * _Nonnull)value;
- (void)addItems:(NSSet * _Nonnull)values;
- (void)removeItems:(NSSet * _Nonnull)values;
@end


@interface Catalog (SWIFT_EXTENSION(PRCatalogModel))
- (void)addEntitiesObject:(CatalogEntity * _Nonnull)value;
- (void)removeEntitiesObject:(CatalogEntity * _Nonnull)value;
- (void)addEntities:(NSSet * _Nonnull)values;
- (void)removeEntities:(NSSet * _Nonnull)values;
@end


@interface Catalog (SWIFT_EXTENSION(PRCatalogModel))
- (BOOL)isEmpty SWIFT_WARN_UNUSED_RESULT;
@end


@interface Catalog (SWIFT_EXTENSION(PRCatalogModel))
- (BOOL)hasFeatured SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasHotspot SWIFT_WARN_UNUSED_RESULT;
@end

@class HubNavigation;

@interface Catalog (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSDate * _Nonnull created;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) BOOL preloaded;
@property (nonatomic, copy) NSSet<CatalogEntity *> * _Nullable entities;
@property (nonatomic, strong) HubNavigation * _Nullable navigation;
@property (nonatomic, copy) NSSet<CatalogItem *> * _Nullable items;
@end





@class RelationshipMetadata;

@interface CatalogEntity (SWIFT_EXTENSION(PRCatalogModel))
- (void)addItemsMetadataObject:(RelationshipMetadata * _Nonnull)value;
- (void)removeItemsMetadataObject:(RelationshipMetadata * _Nonnull)value;
- (void)addItemsMetadata:(NSSet * _Nonnull)values;
- (void)removeItemsMetadata:(NSSet * _Nonnull)values;
@end


@interface CatalogEntity (SWIFT_EXTENSION(PRCatalogModel))
- (void)addSubEntitiesObject:(CatalogEntity * _Nonnull)value;
- (void)removeSubEntitiesObject:(CatalogEntity * _Nonnull)value;
- (void)addSubEntities:(NSSet * _Nonnull)values;
- (void)removeSubEntities:(NSSet * _Nonnull)values;
@end


@interface CatalogEntity (SWIFT_EXTENSION(PRCatalogModel))
- (void)addItemsObject:(CatalogItem * _Nonnull)value;
- (void)removeItemsObject:(CatalogItem * _Nonnull)value;
- (void)addItems:(NSSet * _Nonnull)values;
- (void)removeItems:(NSSet * _Nonnull)values;
@end

@class NSIndexSet;
@class NSOrderedSet;

@interface CatalogEntity (SWIFT_EXTENSION(PRCatalogModel))
- (void)insertObject:(CatalogEntity * _Nonnull)value inSuperEntitiesAtIndex:(NSInteger)idx;
- (void)removeObjectFromSuperEntitiesAtIndex:(NSInteger)idx;
- (void)insertSuperEntities:(NSArray<CatalogEntity *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeSuperEntitiesAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInSuperEntitiesAtIndex:(NSInteger)idx withObject:(CatalogEntity * _Nonnull)value;
- (void)replaceSuperEntitiesAtIndexes:(NSIndexSet * _Nonnull)indexes withSuperEntities:(NSArray<CatalogEntity *> * _Nonnull)values;
- (void)addSuperEntitiesObject:(CatalogEntity * _Nonnull)value;
- (void)removeSuperEntitiesObject:(CatalogEntity * _Nonnull)value;
- (void)addSuperEntities:(NSOrderedSet * _Nonnull)values;
- (void)removeSuperEntities:(NSOrderedSet * _Nonnull)values;
@end


@interface CatalogEntity (SWIFT_EXTENSION(PRCatalogModel))
- (void)insertObject:(CatalogItem * _Nonnull)value inLoadedItemsAtIndex:(NSInteger)idx;
- (void)removeObjectFromLoadedItemsAtIndex:(NSInteger)idx;
- (void)insertLoadedItems:(NSArray<CatalogItem *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeLoadedItemsAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInLoadedItemsAtIndex:(NSInteger)idx withObject:(CatalogItem * _Nonnull)value;
- (void)replaceLoadedItemsAtIndexes:(NSIndexSet * _Nonnull)indexes withLoadedItems:(NSArray<CatalogItem *> * _Nonnull)values;
- (void)addLoadedItemsObject:(CatalogItem * _Nonnull)value;
- (void)removeLoadedItemsObject:(CatalogItem * _Nonnull)value;
- (void)addLoadedItems:(NSOrderedSet * _Nonnull)values;
- (void)removeLoadedItems:(NSOrderedSet * _Nonnull)values;
@end


@class CompoundNavigation;
@class CatalogFilter;
@class CatalogLoading;

@interface CatalogEntity (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable details;
@property (nonatomic, copy) NSString * _Nullable accountName;
@property (nonatomic, strong) Catalog * _Nullable catalog;
@property (nonatomic, strong) CompoundNavigation * _Nullable navigation;
@property (nonatomic, strong) CatalogFilter * _Nullable filter;
@property (nonatomic, strong) Catalog * _Nullable hub;
@property (nonatomic, copy) NSSet<CatalogItem *> * _Nullable items;
@property (nonatomic, strong) NSSet * _Nullable itemsMetadata;
@property (nonatomic, strong) NSOrderedSet * _Nullable loadedItems;
@property (nonatomic, strong) CatalogLoading * _Nullable loading;
@property (nonatomic, strong) NSSet * _Nullable subEntities;
@property (nonatomic, strong) NSOrderedSet * _Nullable superEntities;
@end


SWIFT_CLASS_NAMED("CatalogFilter")
@interface CatalogFilter : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class CatalogNavigation;

@interface CatalogFilter (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) CatalogNavigation * _Nonnull navigator;
@end







@interface CatalogItem (SWIFT_EXTENSION(PRCatalogModel))
- (void)addContentsObject:(CatalogItemContent * _Nonnull)value;
- (void)removeContentsObject:(CatalogItemContent * _Nonnull)value;
- (void)addContents:(NSSet * _Nonnull)values;
- (void)removeContents:(NSSet * _Nonnull)values;
@end


@interface CatalogItem (SWIFT_EXTENSION(PRCatalogModel))
- (void)addEntitiesMetadataObject:(RelationshipMetadata * _Nonnull)value;
- (void)removeEntitiesMetadataObject:(RelationshipMetadata * _Nonnull)value;
- (void)addEntitiesMetadata:(NSSet * _Nonnull)values;
- (void)removeEntitiesMetadata:(NSSet * _Nonnull)values;
@end


@interface CatalogItem (SWIFT_EXTENSION(PRCatalogModel))
- (void)addLoadingEntitiesObject:(CatalogEntity * _Nonnull)value;
- (void)removeLoadingEntitiesObject:(CatalogEntity * _Nonnull)value;
- (void)addLoadingEntities:(NSSet * _Nonnull)values;
- (void)removeLoadingEntities:(NSSet * _Nonnull)values;
@end


@interface CatalogItem (SWIFT_EXTENSION(PRCatalogModel))
- (CatalogItemContent * _Nullable)contentWithOptions:(CatalogItemContentOption * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isInMyLibraryWithContentOptions:(CatalogItemContentOption * _Nonnull)contentOptions SWIFT_WARN_UNUSED_RESULT;
@end


@interface CatalogItem (SWIFT_EXTENSION(PRCatalogModel))
- (void)insertObject:(CatalogEntity * _Nonnull)value inEntitiesAtIndex:(NSInteger)idx;
- (void)removeObjectFromEntitiesAtIndex:(NSInteger)idx;
- (void)insertEntities:(NSArray<CatalogEntity *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeEntitiesAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInEntitiesAtIndex:(NSInteger)idx withObject:(CatalogEntity * _Nonnull)value;
- (void)replaceEntitiesAtIndexes:(NSIndexSet * _Nonnull)indexes withEntities:(NSArray<CatalogEntity *> * _Nonnull)values;
- (void)addEntitiesObject:(CatalogEntity * _Nonnull)value;
- (void)removeEntitiesObject:(CatalogEntity * _Nonnull)value;
- (void)addEntities:(NSOrderedSet * _Nonnull)values;
- (void)removeEntities:(NSOrderedSet * _Nonnull)values;
@end



@class Downloads;
@class HotSpot;
@class PurchaseInfo;

@interface CatalogItem (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable language;
@property (nonatomic) int32_t pageCount;
@property (nonatomic) BOOL rightToLeft;
@property (nonatomic, copy) NSString * _Nonnull slug;
@property (nonatomic) int32_t state;
@property (nonatomic, copy) NSString * _Nullable thumbnailId;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) Catalog * _Nullable catalog;
@property (nonatomic, strong) NSSet * _Nullable contents;
@property (nonatomic, strong) Downloads * _Nullable downloads;
@property (nonatomic, strong) NSOrderedSet * _Nullable entities;
@property (nonatomic, strong) NSSet * _Nullable entitiesMetadata;
@property (nonatomic, strong) HotSpot * _Nullable hotSpot;
@property (nonatomic, strong) NSSet * _Nullable loadingEntities;
@property (nonatomic, strong) PurchaseInfo * _Nullable purchaseInfo;
@property (nonatomic, copy) NSDate * _Nullable date;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable countryCodes;
@end





@interface CatalogItemContent (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) int16_t type;
@property (nonatomic) int16_t options;
@property (nonatomic) BOOL isDownloaded;
@property (nonatomic) int16_t viewerPage;
@property (nonatomic, strong) CatalogItem * _Nonnull catalogItem;
@property (nonatomic, copy) NSDate * _Nullable offlineAccessDate;
@end


SWIFT_RESILIENT_CLASS("_TtC14PRCatalogModel24CatalogItemContentOption")
@interface CatalogItemContentOption : _PROptionSet
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CatalogItemContentOption * _Nonnull none;)
+ (CatalogItemContentOption * _Nonnull)none SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CatalogItemContentOption * _Nonnull sample;)
+ (CatalogItemContentOption * _Nonnull)sample SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CatalogItemContentOption * _Nonnull newContent;)
+ (CatalogItemContentOption * _Nonnull)newContent SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithRawValue:(NSInteger)rawValue OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CatalogLoading")
@interface CatalogLoading : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface CatalogLoading (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSDate * _Nonnull date;
@property (nonatomic) int32_t offset;
@property (nonatomic) int32_t totalCount;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t failureCount;
@property (nonatomic, strong) CatalogEntity * _Nonnull catalogEntity;
@property (nonatomic, copy) NSString * _Nullable continuationToken;
@end


SWIFT_CLASS_NAMED("CatalogNavigation")
@interface CatalogNavigation : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS_NAMED("CompoundNavigation")
@interface CompoundNavigation : CatalogNavigation
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface CompoundNavigation (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) CatalogEntity * _Nonnull scope;
@end


SWIFT_CLASS_NAMED("ContentLicense")
@interface ContentLicense : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class NSURL;
@class NSData;

@interface ContentLicense (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSDate * _Nonnull start;
@property (nonatomic, copy) NSDate * _Nonnull end;
@property (nonatomic, copy) NSURL * _Nullable statusUrl;
@property (nonatomic, strong) CatalogItemContent * _Nonnull content;
@property (nonatomic, copy) NSURL * _Nonnull contentUrl;
@property (nonatomic, copy) NSData * _Nullable encryptionKey;
@property (nonatomic, copy) NSString * _Nullable contentHash;
@property (nonatomic, copy) NSString * _Nullable userContext;
@end


SWIFT_CLASS_NAMED("EPubLocator")
@interface EPubLocator : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ContentLocator")
@interface ContentLocator : EPubLocator
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ContentLocator (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) BookContent * _Nonnull content;
@end


SWIFT_CLASS_NAMED("ContentPage")
@interface ContentPage : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class PageElement;

@interface ContentPage (SWIFT_EXTENSION(PRCatalogModel))
- (void)addElementsObject:(PageElement * _Nonnull)value;
- (void)removeElementsObject:(PageElement * _Nonnull)value;
- (void)addElements:(NSSet<PageElement *> * _Nonnull)values;
- (void)removeElements:(NSSet<PageElement *> * _Nonnull)values;
@end

@class DocumentContent;

@interface ContentPage (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic) int32_t height;
@property (nonatomic, copy) NSString * _Nullable imageId;
@property (nonatomic) int16_t number;
@property (nonatomic) int32_t width;
@property (nonatomic, strong) DocumentContent * _Nonnull documentContent;
@property (nonatomic, copy) NSSet<PageElement *> * _Nullable elements;
@end


SWIFT_CLASS_NAMED("Country")
@interface Country : CatalogEntity
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("Document")
@interface Document : CatalogItem
@property (nonatomic, readonly, strong) DocumentContent * _Nullable documentContent;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Document (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic) int64_t ownerId;
@end


SWIFT_CLASS_NAMED("DocumentContent")
@interface DocumentContent : CatalogItemContent
- (void)didTurnIntoFault;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface DocumentContent (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) NSOrderedSet * _Nullable pages;
@end


@interface DocumentContent (SWIFT_EXTENSION(PRCatalogModel))
- (void)insertObject:(ContentPage * _Nonnull)value inPagesAtIndex:(NSInteger)idx;
- (void)removeObjectFromPagesAtIndex:(NSInteger)idx;
- (void)insertPages:(NSArray<ContentPage *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removePagesAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInPagesAtIndex:(NSInteger)idx withObject:(ContentPage * _Nonnull)value;
- (void)replacePagesAtIndexes:(NSIndexSet * _Nonnull)indexes withPages:(NSArray<ContentPage *> * _Nonnull)values;
- (void)addPagesObject:(ContentPage * _Nonnull)value;
- (void)removePagesObject:(ContentPage * _Nonnull)value;
- (void)addPages:(NSOrderedSet * _Nonnull)values;
- (void)removePages:(NSOrderedSet * _Nonnull)values;
@end


SWIFT_CLASS_NAMED("Downloads")
@interface Downloads : NSManagedObject
+ (Downloads * _Nonnull)instance:(NSManagedObjectContext * _Nonnull)context SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSArray<CatalogItem *> * _Nullable catalogItems;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface Downloads (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) NSOrderedSet * _Nullable items;
@end


@interface Downloads (SWIFT_EXTENSION(PRCatalogModel))
- (void)insertObject:(CatalogItem * _Nonnull)value inItemsAtIndex:(NSInteger)idx;
- (void)removeObjectFromItemsAtIndex:(NSInteger)idx;
- (void)insertItems:(NSArray<CatalogItem *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeItemsAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInItemsAtIndex:(NSInteger)idx withObject:(CatalogItem * _Nonnull)value;
- (void)replaceItemsAtIndexes:(NSIndexSet * _Nonnull)indexes withItems:(NSArray<CatalogItem *> * _Nonnull)values;
- (void)addItemsObject:(CatalogItem * _Nonnull)value;
- (void)removeItemsObject:(CatalogItem * _Nonnull)value;
- (void)addItems:(NSOrderedSet * _Nonnull)values;
- (void)removeItems:(NSOrderedSet * _Nonnull)values;
@end




@interface EPubLocator (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSString * _Nonnull href;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic) int64_t position;
@property (nonatomic) int64_t relativePosition;
@property (nonatomic, copy) NSString * _Nullable partialCfi;
@end


SWIFT_CLASS_NAMED("FragmentEndLocator")
@interface FragmentEndLocator : EPubLocator
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface FragmentEndLocator (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) BookFragment * _Nonnull fragment;
@end


SWIFT_CLASS_NAMED("FragmentStartLocator")
@interface FragmentStartLocator : EPubLocator
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface FragmentStartLocator (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) BookFragment * _Nonnull fragment;
@end


SWIFT_CLASS_NAMED("Genre")
@interface Genre : CatalogEntity
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("Highlight")
@interface Highlight : BookFragment
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface Highlight (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull color;
@end


SWIFT_CLASS_NAMED("HotSpot")
@interface HotSpot : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface HotSpot (SWIFT_EXTENSION(PRCatalogModel))
- (void)addCatalogItemsObject:(CatalogItem * _Nonnull)value;
- (void)removeCatalogItemsObject:(CatalogItem * _Nonnull)value;
- (void)addCatalogItems:(NSSet * _Nonnull)values;
- (void)removeCatalogItems:(NSSet * _Nonnull)values;
@end


@interface HotSpot (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable industry;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, strong) NSSet * _Nullable catalogItems;
@end


SWIFT_CLASS_NAMED("HubNavigation")
@interface HubNavigation : CatalogNavigation
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface HubNavigation (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) Catalog * _Nonnull scope;
@end


SWIFT_CLASS_NAMED("RelationshipMetadata")
@interface RelationshipMetadata : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ItemSeriesMetadata")
@interface ItemSeriesMetadata : RelationshipMetadata
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ItemSeriesMetadata (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSString * _Nonnull position;
@end



SWIFT_CLASS_NAMED("Language")
@interface Language : CatalogEntity
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("TitleItem")
@interface TitleItem : CatalogItem
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("Magazine")
@interface Magazine : TitleItem
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("Newspaper")
@interface Newspaper : TitleItem
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("PageArea")
@interface PageArea : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface PageArea (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic) double x;
@property (nonatomic) double y;
@property (nonatomic) double width;
@property (nonatomic) double height;
@property (nonatomic, strong) PageElement * _Nonnull element;
@end


SWIFT_CLASS_NAMED("PageElement")
@interface PageElement : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface PageElement (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) ContentPage * _Nonnull page;
@property (nonatomic, strong) NSOrderedSet * _Nullable areas;
@end


@interface PageElement (SWIFT_EXTENSION(PRCatalogModel))
- (void)insertObject:(PageArea * _Nonnull)value inAreasAtIndex:(NSInteger)idx;
- (void)removeObjectFromAreasAtIndex:(NSInteger)idx;
- (void)insertAreas:(NSArray<PageArea *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeAreasAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInAreasAtIndex:(NSInteger)idx withObject:(PageArea * _Nonnull)value;
- (void)replaceAreasAtIndexes:(NSIndexSet * _Nonnull)indexes withAreas:(NSArray<PageArea *> * _Nonnull)values;
- (void)addAreasObject:(PageArea * _Nonnull)value;
- (void)removeAreasObject:(PageArea * _Nonnull)value;
- (void)addAreas:(NSOrderedSet * _Nonnull)values;
- (void)removeAreas:(NSOrderedSet * _Nonnull)values;
@end


SWIFT_CLASS_NAMED("PageHyperlink")
@interface PageHyperlink : PageElement
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface PageHyperlink (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSString * _Nonnull url;
@end


SWIFT_CLASS_NAMED("PressCatalog")
@interface PressCatalog : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@class Publications;

@interface PressCatalog (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) Books * _Nullable books;
@property (nonatomic, strong) Publications * _Nullable publications;
@end


SWIFT_CLASS_NAMED("PublicationType")
@interface PublicationType : CatalogEntity
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("Publications")
@interface Publications : Catalog
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Publications (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) PressCatalog * _Nonnull pressCatalog;
@end


SWIFT_CLASS_NAMED("Publisher")
@interface Publisher : CatalogEntity
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("PurchaseInfo")
@interface PurchaseInfo : NSManagedObject
- (void)awakeFromInsert;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface PurchaseInfo (SWIFT_EXTENSION(PRCatalogModel))
/// keep it optional on interface level to eliminate Date._unconditionallyBridgeFromObjectiveC issue due to the dynamic nature of CD objects
@property (nonatomic, copy) NSDate * _Nullable date;
@property (nonatomic, strong) CatalogItem * _Nonnull catalogItem;
@end


SWIFT_CLASS_NAMED("Query")
@interface Query : CatalogEntity
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Query (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, copy) NSString * _Nonnull text;
@end




@interface RelationshipMetadata (SWIFT_EXTENSION(PRCatalogModel))
@property (nonatomic, strong) CatalogEntity * _Nullable catalogEntity;
@property (nonatomic, strong) CatalogItem * _Nullable catalogItem;
@end


SWIFT_CLASS_NAMED("Section")
@interface Section : CatalogEntity
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("Series")
@interface Series : CatalogEntity
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("Supplier")
@interface Supplier : CatalogEntity
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
