ios_version = '15.0'
platform :ios, ios_version

use_frameworks!

target 'PRSDKTest_Pods' do
  pod 'PRSDK'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = ios_version
  end
 end
end
